### ISSUE TITLE
希望入仕年留空時，保存資料時設置默認值為 0

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#10]
北大錄入小組在工作的時候反饋錄入入仕數據時常常碰到沒有入仕時間的狀況，而這種狀況下很容易漏掉入仕時間的錄入。因為入仕時間是 primary key 的一部分，所以會報錯。

錄入小組希望在錄入的時候，當入仕時間沒有被錄入時，能夠將入仕時間自動設置為 0。感謝！

![entry year default value](https://user-images.githubusercontent.com/8538710/50042985-80aef980-00a7-11e9-9c20-1914e94c7401.png)

**Comment by s8714081** [comment]
修改[入仕]表單在保存資料時設置默認值為0，新增完成。
已經更新至bug2分支，commit為'20181217bug2修改[入仕]表單'。
