### ISSUE TITLE
one to many kinship code pairs for kinship input problem

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#103]
**問題本體**

在 CBDB online inputting system 錄入親屬關係的時候，有一個非常方便的機制，即，輸入一個傳主 A 的親屬關係人 B 之後，可以自動透過“成对亲属关系”從 B 的資料中自動建立相對 A 的對應親屬關係：

![image](https://user-images.githubusercontent.com/8538710/96626371-00f8b280-1342-11eb-9c8d-505b549d7201.png)

這裡會有一個問題，CBDB 中親屬的對應關係其實並不是一對一的。譬如，CBDB 中父親的對應親屬關係總共有 49 種：

![image](https://user-images.githubusercontent.com/8538710/96626465-1cfc5400-1342-11eb-8cc1-2afbcb15335a.png)

如果錄入者從父親這一端來錄入時，反向關係就只有“子”和“女”，即 sql query 中拿到的最前面的一條。因此會希望在“成对亲属关系”中不僅拿一條 sql 的 query result，而是在 KINSHIP_CODES 裡面，用 c_kincode 查到所有的（one to many 的） c_kin_pair1 和 c_kin_pair2，把它們輸出到““成对亲属关系”中，讓用戶自行選擇。

**相關問題 1**

這個問題會引出一個潛在的 bug。在親屬關係中，刪除 A 到 B 的親屬關係記錄時，系統同樣也會自動刪除 B 到 A 對應的親屬關係。如果現在的邏輯是 one to one 而不是 one to many，在刪除的時候會不會導致刪錯或者刪不掉對應的關係呢？還想麻煩您檢查一下。辛苦啦~

**相關問題 2**

在當前系統中，錄入完一條親屬關係，點擊 submit 之後，“成对亲属关系”的對應似乎就錯了：
![image](https://user-images.githubusercontent.com/8538710/96627640-bb3ce980-1343-11eb-83de-17e611983c50.png)

這個小問題也麻煩啦~

**相關問題 3**

"成对亲属关系"的正體中文應該是“成對親屬關係”，這個小問題也想麻煩修改一下。

感謝！麻煩啦！

**Comment by s8714081** [comment]
謝謝宏甦經理提供的資訊，先回答[關於相關問題二]的檢查結果。

**[關於相關問題二]：**

檢查程式後發現兩個問題：

1.「成對親屬關係」的資料呈現，是我在抓取錯誤欄位的資料作為呈現（我把兩個欄位的資料呈現都抓到「親屬關係」的值），所以才會兩個都是[父]。但是資料庫中儲存的值是正確的，只有呈現錯誤。
（新增時的資料輸入是正確的，只有開啟編輯畫面時的資料呈現錯誤，所以目前為止輸入的資料都會正確。）

2.我觀察到前輩的寫法，在「親屬關係」與「成對親屬關係」的資料的資料組合時，沒有把[KINSHIP_CODES]資料表的[c_kin_code]值帶到前端介面去，也就是說，第一次新增完「親屬」後，會創建兩筆人物的對應資料，之後都不會修改到這兩筆資料「親屬關係」與「成對親屬關係」的值。

程式說明：

程式的位置：https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/app/Repositories/BiogMainRepository.php

在public function kinshipById($id)函式裡面的558與568行

//557行，代表使用[KIN_DATA]資料表的[c_kin_code]，查詢相關的資料。
$text_ = KinshipCode::find($row->c_kin_code);

//558行，提供給前端的資料呈現組合，由於[$text_->c_status_code]沒有這個欄位，所以資料呈現會是[父 F]。
$kin_str = $text_->c_status_code." ".$text_->c_kinrel_chn." ".$text_->c_kinrel;

**[關於問題一]：**

關於問題一，假如出現這樣一個例子：A 和 B 兩個人物在 CBDB 中有兩筆親屬關係：第一筆是 B 是 A 的兒子；第二筆是 B 是 A 的第三子（後一條比前一條具體）。

這時候我們的錄入者決定刪除其中 B 是 A 的兒子這一條，留下 B 是 A 的第三子。

於是，在刪除 B 是 A 的兒子時，系統會找到 A 是 B 的父親，然而 B 是 A 的第三子的反向關係也同樣是 A 是 B 的父親，這時候會不會導致 B 是 A 的第三子的反向關係被刪除掉呢？

（多對一或多對多的親屬關係都會有相似的狀況）

我創建了這個情境的假資料測試，

刪除 B 是 A 的兒子這一條沒有問題，聯合主鍵是[B(兒子)的 person id] + 親戚姓名(c_kin_id) + 親屬關係(c_kin_code)]組成，可以準確刪除，

刪除反向關係要從程式碼來說明，

1.我先查詢到[B(兒子)的 person id] + 親戚姓名(c_kin_id) + 親屬關係(c_kin_code)]這個物件$row。

2.然後用這個物件的相關資訊查詢反向關係，會多比對[c_source]這個欄位。
$row2 = DB::table('KIN_DATA')->where([
    ['c_kin_id',$row->c_personid],
    ['c_personid', $row->c_kin_id],
    ['c_source', $row->c_source],
])->first();

3.如果出處(c_source)有填寫的情況，可以準確刪除正向與反向關係，如果四筆資料的c_source都沒填寫，則會刪除第一筆被查詢到的資料。

PS：目前版本的程式會將查詢到的反向關係全部刪除（A的兩筆資料都會被刪除），下一版本將更新這個問題。
目前的程式：
DB::table('KIN_DATA')->where([
    ['c_kin_id',$row2->c_kin_id],
    ['c_personid', $row2->c_personid],
    ['c_kin_code', $row2->c_kin_code],  /*這裡需要修改為['c_source', $row2->c_source],*/
])->delete();

PS 宏甦經理建議：
除了 source，還建議加上兩個欄位的資訊：c_created_date 和 c_modified_date。這樣做的第一個 assumption 是：自動建立的反向關係一定是建立正向關係的瞬間建立的，所以兩者應該是同一天建立的。第二個 assumption 是：同一天根據同一個 source 建立同一個人兩筆重覆的資料（如子和第三子）幾率非常非常的低。所以這樣來設置刪除的條件基本能確保萬無一失。

**Comment by sudoghut** [comment]
包老師在錄入的時候發現了一個小 bug，還想麻煩您方便的時候修一下呢。

在呂大猷（Lv Dayou）- 17904 的親屬資料中：http://47.114.119.106:8000/basicinformation/17904/kinship/17904-3652-131/edit
 
![image](https://user-images.githubusercontent.com/8538710/97737442-fa272800-1b17-11eb-992b-dbc392fb73e8.png)

從兄（131）的親屬關係（416）只有從妹，而在當前的 kinship_codes 表中，131 對應的 pairs 有 130（從弟）和 416（從妹）：
http://47.114.119.106:8000/codes/kinship_codes/131/edit

![image](https://user-images.githubusercontent.com/8538710/97737511-14610600-1b18-11eb-9cc0-1f0b75c7960f.png)

希望能在親屬關係中錄入 131 從兄時，成對親屬關係可以顯示 130（從弟）和 416（從妹）。

奇怪的是，我用 75（父親）來測試的時候，好像這個 bug 就不存在了。即使在錄入完成之後的修改界面裡面，我只要再選一次 75，對應的關係也能正常顯示。

感謝您！

**Comment by s8714081** [comment]
20201102修正[成對親屬關係]初次載入

問題回應：

第一次進入[親屬]編輯畫面時，[成對親屬關係]一開始的載入，是以KIN_DATA資料表的值為優先，KIN_DATA資料表中c_kin_id等於當前c_personid，這筆資料的c_kin_code值，來作為[成對親屬關係]的資料呈現。

還沒有去讀取 KINSHIP_CODES 的資料來組合選項（下拉式選單），等到[親屬關係]有異動，例如將[從兄]換成[父]，這樣[成對親屬關係]的下拉式選單才會動態組合。

這樣做的原因，是[成對親屬關係]原本儲存的值，如果不在動態組合的下拉式選單中，還是可以正確呈現與儲存，適用於前版[親屬]錄入表單的情境。

例如：[親屬關係]選取父，[成對親屬關係]有[子]、[女]，但是KIN_DATA資料表的值是紀錄[父]與[三子]，這樣就可以正確呈現並維持修改時儲存正確。

修改方向：

1.改善原本的流程，保留原本儲存的值，如果不在動態組合的下拉式選單中，還是可以正確呈現與儲存，並在一開始就先判別[親屬關係]的值，先動態組合出[成對親屬關係]的下拉式選單，直接先去讀取 KINSHIP_CODES 的資料來組合選項（下拉式選單），疊加至原本儲存的值底下。

2.測試方案，一開始就先判別[親屬關係]的值，先動態組合出[成對親屬關係]的下拉式選單，直接先去讀取 KINSHIP_CODES 的資料來組合選項（下拉式選單），不需疊加至原本儲存的值底下，直接呈現選項，檢測是否能符合所有情境。（初始值selected不易判別，維持[修改方向-1]的做法。）
