### ISSUE TITLE
新增著作版本表及 TEXT_DATA 表改名

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#106]
建安，

最近我們著手在 Edith Enright 和 陳松重新設計基礎上實施著作相關表的重構。

**1 新增著作版本表**

這是我們新增的一個著作版本表 text_instance_data table 的 SQL dump:

[text_instance_data.zip](https://github.com/cbdb-project/cbdb-online-main-server/files/5474623/text_instance_data.zip)

還想麻煩您幫忙協助來建立著作版本表的錄入，感謝！這個表的位置是在“著作編碼表的下面”

![image](https://user-images.githubusercontent.com/8538710/97864569-be70a600-1d43-11eb-82a7-d261c3218c81.png)

“操作”有 edit 和 delete 兩種。另外還想麻煩您在著作編碼表的的操作中添加一個 delete 按鈕，麻煩啦~

http://47.114.119.106:8000/textcodes

![image](https://user-images.githubusercontent.com/8538710/97864947-61c1bb00-1d44-11eb-8e6f-02e061952771.png)

學者進入 edit 之後，界面上各欄位的名稱沿用 SQL datadump 導入後的英文欄位名即可。因為這個表我們只是給熟悉 CBDB 結構的研究者和維護者，不希望中文的名稱給誤入此頁面的編輯者造成誤導。之後根據使用者的反饋，我們再確定是否要把一些欄位設計成下拉菜單查詢式的。

**2 TEXT_DATA 改名**

我們這次重構把 TEXT_DATA 表重命名為 BIOG_TEXT_DATA，還想麻煩建安在本地的測試資料庫中也改一下名稱，並在這次 pull request 中把代碼中所有 TEXT_DATA 重命名為 BIOG_TEXT_DATA。等這次合併分支之後，我會在 production environment 中也一併改名，並且在改名之後，把整個資料庫的 datadump 傳送給您一份。

**3 預告**

此階段接下來對出處系列表的改動大多是小改動，唯一的大改動是著述錄入界面的變更。http://47.114.119.106:8000/basicinformation/17904/texts/create 具體修改等這次修改合併分支後再麻煩您啦。

感謝！
Hongsu

**Comment by sudoghut** [comment]
Dear 建安：
萬分感謝！已經合併分支並推送至 production environment.
另外，還希望能追加兩個改動：1 將“著作版本表”的“查詢著作類型” label 的內容改成“查詢著作版本”；2 添加一個“新增”按鈕，以便錄入者可以新增著作版本。（見下圖）
 
![image](https://user-images.githubusercontent.com/8538710/98815959-e4dcc280-2462-11eb-8573-fb3247cb6583.png)

抱歉之前設計時考慮不周，遺留下來這兩個問題。麻煩您啦。

感謝，
Hongsu

**Comment by s8714081** [comment]
[查詢著作版本]的[新增]功能與查詢欄位label修改
需請將資料庫中TEXT_INSTANCE_DATA資料表的[外鍵限制]刪除，請點選[結構]>[關聯檢視]，
可以看到這邊有一組[外鍵限制]，這組[外鍵限制]的設定會影響[新增]功能，修改與刪除不被影響，
這次程式更新的[新增]功能，需要移除這組[外鍵限制]，功能才會正常。
![image](https://user-images.githubusercontent.com/6869447/98881937-1f2b7b80-24c6-11eb-9b49-d25ea44c2be1.png)

**Comment by sudoghut** [comment]
感謝建安的高效修復！已經合併至 production environment.

關於版本的邏輯是這樣的：首先要有一本書（TEXT_CODE），才能夠有這本書的一個版本（TEXT_INSTANCE_DATA）。所以當前 foreign key 的機制是運作正常的。

在實際操作中， 當錄入者要錄入一本書的時候：

1. 先到 TEXT_CODE 錄入這本書的資訊，如果這本書沒有詳細的版本資訊，操作到此為止。

2. 如果錄入者需要錄入這本書詳細的版本資訊，需要從 TEXT_CODE 表中複製新建這本書的 c_textid 到 TEXT_INSTANCE_DATA 表的“新建”功能中，粘貼成為  TEXT_INSTANCE_DATA 表的 c_textid 資訊。這樣一本抽象的書（可以理解成一個 class）和一本具體的書（可以理解成一個 instance）就關聯起來了。

3. 當錄入者在 TEXT_CODES 表裡面刪除一本書的時候，它的所有版本因為 foreign key 的束縛，得以自動刪除掉。在邏輯上：如果一個 class 不存在，它的 instances 應該全部被銷毀。（更新亦如此）

4. 當用戶直接在 TEXT_INSTANCE_DATA 中錄入一本書的時候，當前的 foreign key 機制剛好可以擋住這樣的操作。因為在邏輯上：我們需要先建立 class，然後才能由 class 來生成 instances。反之是 illegal 的。

基於這個邏輯，會建議在“著作版本表”中新建記錄時，c_textid 欄位直接留空： 

![image](https://user-images.githubusercontent.com/8538710/98958529-57ba6c00-253d-11eb-8e87-db511e72eb9b.png)

特別感謝建安對這個問題非常主動而且特別細心的思考~

**Comment by s8714081** [comment]
謝謝宏甦經理的詳細說明，依據TEXT_CODES與TEXT_INSTANCE_DATA的邏輯，在[著作版本表]中新建記錄時，c_textid欄位保留空白，並在前端與後端的程式做了提示與防護。

1.前端提醒使用者，請先從TEXT_CODES表中複製這本書的c_textid填入。
![image](https://user-images.githubusercontent.com/6869447/99208063-71d4a280-27fa-11eb-999f-40742c27915f.png)

2.後端防護措施，c_textid未填或重複填寫，提示訊息。
![image](https://user-images.githubusercontent.com/6869447/99208075-79944700-27fa-11eb-927f-2ad5c1257795.png)
