### ISSUE TITLE
基本資料增加 index year 推算欄位

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#111]
在這次更新的資料庫結構中，BIOG_MAIN 表添加了兩個欄位： c_index_year_type_code，c_index_year_source_id。這兩個欄位的資訊希望可以展示在“基本資料”頁面上。譬如：
http://47.114.119.106:8000/basicinformation/1762/edit
![image](https://user-images.githubusercontent.com/8538710/100272613-6cafea00-2f96-11eb-97b9-68171177fe73.png)

細則：

1. “指數年推算方法(c_index_year_type_code)” 右側 inputbox 內容是 c_index_year_type_code 再加上用此 code join INDEXYEAR_TYPE_CODES 表中 c_index_year_type_code 欄位，查到的 “c_index_year_type_hz” 欄位的內容。例如王安石(personid=1762)的例子，“指數年推算方法(c_index_year_type_code) ” 右側 inputbox 顯示的內容是 “01 據生年” 。

2. “指數年推算來源 id(c_index_year_source_id)”右側 inputbox 的內容是 c_index_year_source_id，再加上用此 id join BIOG_MAIN 表中 c_personid 的內容。例如安燾(personid=3)的例子，“指數年推算來源 id(c_index_year_source_id)”右側 inputbox 顯示的內容是“3001 安日華”。

3. 新增的這兩個欄位對應的 inputbox 希望設定為無法編輯。此外，同為“基本資料”頁面上的“指數年(index year)”也希望設定為無法編輯。（因為我們每次更新時都會抹掉這三個欄位原本的內容，重新自動生成它們）

感謝！

**Comment by s8714081** [comment]
[排版]
錄入系統的版面採取網格系統12格（RWD），本次欄位的排版採用2.4.2.4，在對齊上會更優雅一些。

[c_index_year_type_code] 欄位值複數
在程式中如果遇到複數的值，統一取前兩位的值，用來查詢INDEXYEAR_TYPE_CODES 資料表。
