### ISSUE TITLE
社會關係界面異動，c_secondary_source_author 新欄位，以及 TEXT_CODES 表大異動

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#119]
**首先是社會關係界面異動兩處。**

第一處是，在社會關係錄入界面中，我發現長久以來這個界面缺少了一個欄位：c_inst_name_code。它的 label 應該是：社交機構名稱代碼(c_inst_name_code)。
http://47.114.119.106:8000/basicinformation/1/assoc/create
 
![image](https://user-images.githubusercontent.com/8538710/105392781-8e57e580-5c56-11eb-8302-719709094182.png)

內容是 ASSOC_DATA 表的 c_inst_name_code 的內容 join 到 SOCIAL_INSTITUTION_NAME_CODES 表的 c_inst_name_code 欄位，查到 c_inst_name_hz 欄位的內容。然後用 c_inst_name_code  c_inst_name_hz c_inst_name_py 拼合成下拉菜單的內容。形如：10 白鷲洲書院 Baijiuzhou shuyuan。

第二處是，剛剛提到的第一處社交機構名稱代碼（c_inst_name_code），以及社交機構代碼（c_inst_code）在錄入界面中希望直接設定為默認值 = 0。

**其次是 c_secondary_source_author 新欄位。**

經過討論，CBDB 決定在二十個表中添加一個文本類型新欄位 c_secondary_source_author，中文是“二手文獻的原作者”。（已在 datadump 中添加，“TEXT_CODES 表大異動”會提到這個 datadump）第三是，其中涉及到在線錄入系統界面的有十二處：

altname_data（別名）
assoc_data（社會關係）
biog_addr_data（地址）
biog_inst_data（社交機構）
biog_source_data（出處）
biog_text_data（著述）
entry_data（入仕）
events_data（事件）
kin_data（親屬）
possession_data（財產）
posted_to_office_data（官名）
status_data（社會區分）

c_secondary_source_author 和 c_source, c_pages 是一組，界面樣式設計建議是（可視情況靈活改動）：

![image](https://user-images.githubusercontent.com/8538710/105395405-a67d3400-5c59-11eb-8662-9693b5d2c88a.png)

**第三是， TEXT_CODES 表大異動。**

之前提到，最近我們的 database restructure 主要會圍繞著 TEXT 表進行。當下便是 Phase 2. 我們將大量和版本相關的欄位從 TEXT_CODES 表移動到了 TEXT_INSTANCE_DATA 表。不過這個改動不會影響到在線錄入系統的界面。所以第三條不需要任何代碼工作。唯一要做的是，我會把 CBDB MySQL 的 datadump 發送給您，您更新一下本地的 MySQL database 即可。

感謝建安！有任何疑問我們隨時溝通。

**Comment by sudoghut** [comment]
1. 正如您在 Issues 119「社交機構名稱代碼(c_inst_name_code)新增」的問題討論.docx 中的疑惑，當前的代碼邏輯是錯誤的。這裡錯誤的邏輯用把 c_inst_code 當成了 c_inst_name_code，查詢出來的內容肯定是不對的。

正確的邏輯是，在「社會關係」表單中從「社交機構代碼(c_inst_code)」，取得 [c_inst_code]。用  [c_inst_code] 向 [SOCIAL_INSTITUTION_CODES] 表查詢取得 [c_inst_name_code] ，用 [c_inst_name_code] 到 [SOCIAL_INSTITUTION_NAME_CODES] 資料表查詢 [c_inst_name_code]，取得它的漢字 [c_inst_name_hz]。

邏輯梳理完成之後，我忽然意識到，其實在「社會關係」表單中的「社交機構代碼(c_inst_code)」已經包含了 [c_inst_name_code] 資訊。我們是否可以將需求修改為：不添加一個新的  [c_inst_name_code] 錄入，而是把「社會關係」表單中的「社交機構代碼(c_inst_code)」改名為 「社交機構(social_institution)」，學者在錄入的時候，只要錄入一次，就能同時寫入 ASSOC_DATA 表的  c_inst_code 和  c_inst_name_code 兩個欄位呢？（唯一可能需要注意的是，同一個 c_inst_code 可能對應多個中文 c_inst_name_code。在用戶選擇的時候，把它們都列出來就行了。）麻煩建安評估了呢。譬如，如果這樣做會不會違背了 data binding 原則，可能為未來維護帶來額外的麻煩之類的問題。

2. 關於“最後確認的名稱是「社交機構代碼(c_inst_code)」與「社交機構名稱代碼(c_inst_name_code)」對不對”。

實在抱歉 Issues 中的筆誤。現在已經改過來了。這裡確認，涉及到「社交機構」的地方，我們都不用社會這個詞。

**Comment by s8714081** [comment]
說明：

a.新增[二手文獻的原作者]欄位至12項（altname_data（別名）、assoc_data（社會關係）...等）錄入表單。

b.經討論後，將需求修改為：不添加一個新的 [c_inst_name_code] 錄入，而是把「社會關係」表單中的「社交機構代碼(c_inst_code)」改名為 「社交機構(social_institution)」，學者在錄入的時候，只要錄入一次，就能同時寫入 ASSOC_DATA 表的 [c_inst_code] 和 [c_inst_name_code] 兩個欄位。

製作步驟：

b-1.新增一組下拉式選單的 [socialinstcode] API，依據 [SOCIAL_INSTITUTION_CODES] 資料表組合資料，輸出內容為「社交機構代碼 - 社交機構名稱 - 社會機構名稱代碼 - 地址 - 起年 - 最早見諸文獻年 - 訖年 - 最晚見諸文獻年」

b-2.在[社會關係錄入界面]儲存社交機構代碼(c_inst_code)的選項後，程式自動依據 [SOCIAL_INSTITUTION_CODES] 資料表中， [c_inst_code] 對應的 [c_inst_name_code]，自動將值儲存至 [ASSOC_DATA] 資料表的 [c_inst_name_code] 欄位。

總結：

新增[二手文獻的原作者]欄位後，12項（altname_data（別名）、assoc_data（社會關係）...等）錄入表單的CRUD已經測試過，均測試正常，請宏甦經理先測試a項的功能是否正確。

b項的功能請測試是否符合需求？如果有需要調整的地方請跟我說，如果OK，請宏甦經理規劃需修改與調整的錄入表單，我們將在後續的issues進行這個項目。

**Comment by sudoghut** [comment]
感謝！之前在郵件裡面討論過，這裡忘記回復了。是的，如果能實現b項的功能，就太好啦！如果不方便實現，或者邏輯過於複雜，我們可以隨時討論。

**Comment by s8714081** [comment]
(c_inst_code)3885重複值需要兼容，修改socialinstcode API輸出，初步規劃與製作。

1. 表單input變造，原本讀入與儲存為A值，修改為A-B值，有create(檢查後不需修改)與edit(需修改)兩個表單。
2. search API(/api/select/search/socialinstcode)修改，原讀取A值(c_inst_code)改為A(c_inst_code)-B(c_inst_name_code)值，輸出結果也要一起修改。(修改$item['id']，改變這組API回傳的值。)
3. controller修改$request，A值(c_inst_code)欄位取得時，拆解後分別存入A(c_inst_code)、B(c_inst_name_code)欄。
4. 調整BiogMainRepository.php的assocById()、assocStoreById()、assocUpdateById()，三個函式的資料處理。
5. 資料錄入測試，確認ASSOC_DATA儲存的資料正確並成對。

**Comment by sudoghut** [comment]
感謝設計！

**Comment by sudoghut** [comment]
還有一個「歷史遺留問題」想求助建安。在  social_institution_codes 頁面中新增一個社會機構時，會缺少 c_inst_name_code 欄位，如下圖：
http://47.114.119.106:8000/codes/social_institution_codes/create

![image](https://user-images.githubusercontent.com/8538710/110489818-a7dfbe80-812a-11eb-9b31-9b276ed9d359.png)

而後台 c_inst_name_code 欄位是存在的：

![image](https://user-images.githubusercontent.com/8538710/110489889-b75f0780-812a-11eb-9fdb-bdc3ef070784.png)

當時建構這個頁面的時候，可能設計者預想的自動遞增的欄位是 c_inst_name_code，而實際上，這個頁面中應該自動遞增的欄位應該是 c_inst_code。並且正如之前討論過的， c_inst_code 允許相同的值（允許用戶修改），所以希望：

1. 在 social_institution_codes 新增記錄的頁面中，能顯示  c_inst_name_code 欄位；

2. 在 social_institution_codes 新增記錄的頁面中， c_inst_code 值根據當前最大值自動遞增並填充；

3.  在 social_institution_codes 新增記錄的頁面中， c_inst_code 值允許用戶編輯；

麻煩建安啦

**Comment by sudoghut** [comment]
經過兩年工作和討論 c_secondary_source_author，CBDB 學術委員會再次討論之後，我們可能希望刪除 c_secondary_source_author 這個欄位。（相關功能我們會在不存在 c_secondary_source_author 的架構下透過允許把 secondary source 記錄為 source 來實現）實在是麻煩建安了。有任何需要討論的地方，我們隨時溝通。在前台刪除這個欄位之後，我們會在資料庫層面刪除。

**Comment by s8714081** [comment]
20230612移除c_secondary_source_author表單欄位，共計24隻程式。
1.盤點html/resources/，c_secondary_source_author存在於24隻程式，共計有48處。
2.檢查routes/、app/、Repositories/、Controllers/、Api/位置，沒有c_secondary_source_author相關程式碼。
