### ISSUE TITLE
多筆著作版本表錄入

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#163]
當前新建著作版本的界面如下：
https://input.cbdb.fas.harvard.edu/textinstancedata/create
![image](https://user-images.githubusercontent.com/8538710/139488227-8adc1391-9c17-4cc3-b375-72bd6d77330f.png)

而在 TEXT_INSTANCE_DATA 表中，primary keys 是：c_textid, c_text_edition_id, c_text_instance_id

在上面的截圖中，如果要錄入一本書的第二個版本就會導致 c_textid 衝突：

![image](https://user-images.githubusercontent.com/8538710/139488775-184f7b96-26c7-415e-b2e8-add9cad45025.png)

還想拜託建安在新建著作版本的界面上添加 c_text_edition_id （版本 ID）和 c_text_instance_id （版本實例 ID）的輸入框。另外，也把著作版本（textinstancedata）在前端的 primary keys 設置為：c_textid, c_text_edition_id, c_text_instance_id

感謝！

**Comment by s8714081** [comment]
1.在新建著作版本的界面上添加 c_text_edition_id （版本 ID）和 c_text_instance_id （版本實例 ID）的輸入框。
2.另外，也把著作版本（textinstancedata）在前端的 primary keys 設置為：c_textid, c_text_edition_id, c_text_instance_id。
3.git commit -m '20211105多筆著作版本表錄入修改為聯合主鍵'。
申請合併至develop。
