### ISSUE TITLE
addrbelongsdata 修改資訊時的小故障

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#177]
在工作的時候我發現在地址從屬表「addrbelongsdata」中修改地址從屬信息時，系統會報錯。

譬如在這條記錄中：

https://input.cbdb.fas.harvard.edu/addrbelongsdata/300294-300496/edit

希望把 c_belongs_to 從 300496 改成 300507（這條記錄的 300496 其實是正確的，我在 MySQL 後台直接做了修改。而 300507 是修改以前的不正確的地址代碼。這裡只是舉一個例子），系統會報錯如下：

![image](https://user-images.githubusercontent.com/8538710/144266364-537fb565-8383-44aa-98bd-475881442e43.png)

麻煩啦~

**Comment by s8714081** [comment]
修正地址從屬表錄入表單程式錯誤，加強addrbelongsdata聯合主鍵的組合。
