### ISSUE TITLE
著作編碼表添加作者資訊作為錄入參考

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#185]
當前錄入系統中可從作者（人物）透過「著述」頁面檢索到他的著述：

https://input.cbdb.fas.harvard.edu/basicinformation/1762/texts

但是無法從書籍頁面確認此書是否有作者，或作者是誰：

https://input.cbdb.fas.harvard.edu/textcodes/2031/edit

在錄入書籍需要消歧時，能快速確定其作者特別重要。因此希望能在「著作編碼表」頂端添加作者（author）資訊：

https://input.cbdb.fas.harvard.edu/textcodes/4865/edit

![image](https://user-images.githubusercontent.com/8538710/149597818-945cbc9c-967a-4a1e-87c4-f2b0992a3864.png)

以下為作者資訊規格：

1. author 為下拉選單，以便顯示一本書之多位作者、編者。author 下一行添加按鈕「Jump to author」，點擊此按鈕，在新 window 中打開此作者「著述」頁面, URL 建構方法為：[DOMAIN]/basicinformation/[personid]/texts. 如 https://input.cbdb.fas.harvard.edu/basicinformation/11/texts

2. author 下拉選項內容為：人物 personid - 人物中文名 - 人物拼音名 - 人物著作角色
 
2. author 下拉選單的內容查詢方式為：

 - 人物 personid：TEXT_CODES 的 c_textid 欄位查詢到 BIOG_TEXT_DATA 的 c_personid

 - 人物中文名：TEXT_CODES 的 c_textid 欄位查詢到 BIOG_TEXT_DATA 的 c_personid，再用此 c_personid 查詢到 BIOG_MAIN 表的 c_name_chn

 - 人物拼音名：TEXT_CODES 的 c_textid 欄位查詢到 BIOG_TEXT_DATA 的 c_personid，再用此 c_personid 查詢到 BIOG_MAIN 表的 c_name
 
- 人物著作角色：TEXT_CODES 的 c_textid 欄位查詢到 BIOG_TEXT_DATA 的 c_role_id，再用此 c_role_id 查詢到 TEXT_ROLE_CODES 的 c_role_desc_chn

 
4. author 下拉選單為 read only

**Comment by s8714081** [comment]
1.製作API，組合需要的回傳資料。
2.僅「Text Codes 著作編碼表」edit表單製作ajax下拉式選單，依據c_textid查詢。
3.製作前端jQuery觸發按鈕，取得選項value開啟指定新頁。
