### ISSUE TITLE
允許同名社會機構錄入

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#187]
# 機制

在社會機構表 SOCIAL_INSTITUTION_CODES 中有兩個重要的 codes，一個是 c_inst_name_code 一個是 c_inst_code. 見：

https://input.cbdb.fas.harvard.edu/socialinstitutioncodes/1547-2523-2/edit

c_inst_name_code 用來記錄社會機構不同的名字。而 c_inst_code 用來記錄每個社會機構的個體。

譬如歷史各地上有多個「白蓮寺」，這些白蓮寺的 c_inst_name_code 就都是相同的（c_inst_name_code = 11），每一個不同的白蓮寺則會有不同的 c_inst_code.

# 問題

在當前的系統中新增一筆「社會機構編碼表」時：

https://input.cbdb.fas.harvard.edu/socialinstitutioncodes/create#

![image](https://user-images.githubusercontent.com/8538710/150882775-2a7dc086-c731-48f9-8809-fcdf40e9e192.png)

![image](https://user-images.githubusercontent.com/8538710/150882737-c8457e12-cca2-4788-9748-5d6e34a53c13.png)

如果填寫在系統中已經存在的 c_inst_name_code，譬如 1547；在 c_inst_code 中填寫一個之前從沒用過的 code，譬如 9999999；在 c_inst_type_code 中填寫任意的 type code，譬如 1：

![image](https://user-images.githubusercontent.com/8538710/150882922-500cc24f-2c5a-485d-9331-39199d6438a9.png)

submit 之後，系統會報錯「c_inst_name_code 未填或已存在」

![image](https://user-images.githubusercontent.com/8538710/150883128-817b7519-c073-49e2-a63c-a4c5e6a1e7d4.png)

# 方案

希望在「社會機構編碼表」https://input.cbdb.fas.harvard.edu/socialinstitutioncodes 中新建資料時，能夠允許基於已經存在的「c_inst_name_code 」來建新的 「c_inst_code」。也許可以考慮和資料庫的 primary keys 一致，把 「c_inst_name_code」與 「c_inst_code」設為 primary keys.

感謝！

**Comment by s8714081** [comment]
原錄入表單有限制[空值]或[重複]，則阻止新增，移除限制[重複]即可，保留限制[空值]，允許同名社會機構錄入。
