### ISSUE TITLE
数据库表怎么构建

### ISSUE THREAD

**Issue by wentian0511** [cbdb-project/cbdb-online-main-server#198]
有构建数据库表DML文件吗？

**Comment by sudoghut** [comment]
您好，绝大多数表都可以从 cbdb_sqlite 中导入：
https://github.com/cbdb-project/cbdb_sqlite

关于和用户和系统相关的表，如果您需要部署在本地、并且是非商业化使用。可以联络我：hongsuwang@fas.harvard.edu.

谢谢你对本项目感兴趣。
