### ISSUE TITLE
錄入系統開發建議 20190110_hs

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#21]
社會關係中 c_text_title（作品標題）primary key 欄位保存時如果為空，則自動補 “[n/a]”

出處的c_pages（頁數/條目） primary key 欄位保存時如果為空，則自动補0

社會區分的c_sequence (次序)primary key 欄位保存時如果為空，則自動補0

入仕方式 c_entry_addr_id 非必填項目，這個必填的判斷需要刪去

親屬關係、社會關係、社會區分和出處當前還是用 tts_sysno，而不是聯合主鍵來檢索。希望變成利用 composite key 來做查詢

社會關係的總覽視圖中希望添加 c_sequence 的資訊

地址編碼表和中國行政地理單位編碼表改名

地址查詢的時候希望組出來地址和上層行政單位

You will find the details in the document attached below

[錄入系統開發建議 20190110_hs.docx](https://github.com/cbdb-project/cbdb-online-main-server/files/2746412/20190110_hs.docx)

**Comment by s8714081** [comment]
修改後的程式推送至bug1支線，commit 20190115錄入系統開發建議I，內容如下：
a.社會關係中 c_text_title（作品標題）primary key 欄位保存時如果為空，則自動補"[n/a]"。
b.出處的 c_pages（頁數/條目） primary key 欄位保存時如果為空，則自動補0。
c.社會區分的 c_sequence（次序）primary key 欄位保存時如果為空，則自動補0。
e.入仕方式 c_entry_addr_id 非必填項目，這個必填的判斷需要刪去。
f.社會關係的總覽視圖中希望添加 c_sequence 的資訊。
g.地址編碼表和中國行政地理單位編碼表改名。
修改說明:
a.自動填補缺失值在前端頁面修改。

**Comment by s8714081** [comment]
製作錄入系統開發建議II，地址查詢的時候希望組出來地址和上層行政單位。
commit 20190116地址查詢時組出地址和上層行政單位
修改說明：搜尋的關鍵字是c_name_chn(中文)、c_name(英文)與c_addr_id(ID)，所以在輸出呈現文字時增加上層地址的相關資訊，而上層地址的ID與中文不可以被檢索，是OK的。
![default](https://user-images.githubusercontent.com/6869447/51221535-d6abe100-1974-11e9-916b-8bf387040d31.PNG)
(圖:搜尋時帶出上層資料)
![default](https://user-images.githubusercontent.com/6869447/51221551-ea574780-1974-11e9-87a6-79992d94b930.png)
(圖:儲存之後將[[]]的內容刪除)

**Comment by s8714081** [comment]
* 20190115錄入系統開發建議I
a.社會關係中 c_text_title（作品標題）primary key 欄位保存時如果為空，則自動補"[n/a]"。
b.出處的 c_pages（頁數/條目） primary key 欄位保存時如果為空，則自動補0。
c.社會區分的 c_sequence（次序）primary key 欄位保存時如果為空，則自動補0。
e.入仕方式 c_entry_addr_id 非必填項目，這個必填的判斷需要刪去。
f.社會關係的總覽視圖中希望添加 c_sequence 的資訊。
g.地址編碼表和中國行政地理單位編碼表改名。
修改說明：自動填補缺失值在前端頁面修改。

* 20190116地址查詢時組出地址和上層行政單位
修改說明：搜尋的關鍵字是c_name_chn(中文)、c_name(英文)與c_addr_id(ID)，所以在輸出呈現文字時增加上層地址的相關資訊，而上層地址的ID與中文不可以被檢索，是OK的。

* 20190118修改親屬關係使用聯合主鍵
修改說明：親屬關係的更新，會執行兩次更新，[人]與[人]之間的親屬資料是連動更新，新增、刪除亦相同。

* 20190121修復基本資料下修改朝代信息
如果把朝代從空白改為"清"，系統會報錯誤訊息。
修改說明：修改BiogMainRepository.php:154行即可。

* 20190122修改社會區分與社會關係使用聯合主鍵

* 20190124修改出處使用聯合主鍵

[錄入系統開發建議 20190110_hs]需求均已完成，如有需要調整的地方請跟我說，謝謝^_^
