### ISSUE TITLE
API double check

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#222]
最近我們對 CBDB API 進行了檢查：
https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md

發現有一些 POST API 無法工作，大多數的報錯是：Trying to access array offset on value of type null. 還想拜託：

七、查詢擔任過給定職官的人
https://input.cbdb.fas.harvard.edu/api/query_people_in_office?RequestPayload:{"office":[920,1022,1023],"useOfficePlace":0,"officePlace":[],"usePeoplePlace":1,"peoplePlace":[2928,10522,12553,13947,13949],"indexYear":1,"indexStartTime":960,"indexEndTime":1250,"useXy":1,"start":11,"list":10}
HS: 這一條在功能上是不是已經被 八、查詢除授記錄（Office Postings）取代？如果是，還想拜託代碼中是否還有殘留，如果沒有殘留。我會直接在 API 中刪除：七、查詢擔任過給定職官的人

九、通過入仕途徑查詢人物
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload:{"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1368,"dynStart":null,"dynEnd":null,"dateEndTime":1644,"useXy":1,"start":1,"list":10}

十、根據給定人物陣列查詢人物親屬
https://input.cbdb.fas.harvard.edu/api/query_relatives_2?RequestPlayload={"people":["3767"],"mCircle":0,"MAncGen":4,"MDecGen":4,"MColLink":2,"MMarLink":1,"MLoop":1,"start":0,"list":65535,"debugMode":1}

十三、查詢人物社會關係
https://input.cbdb.fas.harvard.edu/api/query_associates?RequestPayload:{"association":[22],"place":[101125],"usePeoplePlace":1,"useXy":1,"indexYear":1,"indexStartTime":960,"indexEndTime":1250,"broad":0}

十四、通過地區查詢
https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload:{"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual","entry","officePosting"],"useDate":1,"dateType":"index","dateStartTime":1368,"dateEndTime":1644,"dynStart":null,"dynEnd":null,"useXy":1,"start":1,"list":10}

**Comment by s8714081** [comment]
關於「七、查詢擔任過給定職官的人」確認已經刪除，討論過程的附件另行提供參考。

- 「九、通過入仕途徑查詢人物」請將RequestPayload後面的[冒號:]修改為[等號=]即可，正確網址如下：
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1368,"dynStart":null,"dynEnd":null,"dateEndTime":1644,"useXy":1,"start":1,"list":10}

- 「十、根據給定人物陣列查詢人物親屬」請將RequestPlayload修改為RequestPayload即可，正確網址如下：
https://input.cbdb.fas.harvard.edu/api/query_relatives_2?RequestPayload={"people":["3767"],"mCircle":0,"MAncGen":4,"MDecGen":4,"MColLink":2,"MMarLink":1,"MLoop":1,"start":0,"list":65535,"debugMode":1}
- 備註：["debugMode":1]是代表開啟除錯模式，將["debugMode":0]更改為0，可以看到詳細資料。
https://input.cbdb.fas.harvard.edu/api/query_relatives_2?RequestPayload={"people":["3767"],"mCircle":0,"MAncGen":4,"MDecGen":4,"MColLink":2,"MMarLink":1,"MLoop":1,"start":0,"list":65535,"debugMode":0}

- 「十三、查詢人物社會關係」請將RequestPayload後面的[冒號:]修改為[等號=]即可，正確網址如下：
https://input.cbdb.fas.harvard.edu/api/query_associates?RequestPayload={"association":[22],"place":[101125],"usePeoplePlace":1,"useXy":1,"indexYear":1,"indexStartTime":960,"indexEndTime":1250,"broad":0}

- 「十四、通過地區查詢」請先將RequestPlayload修改為RequestPayload，因為["dateStartTime":1368,"dateEndTime":1644]恰好把資料都過濾了，請調整為["dateStartTime":1200,"dateEndTime":1644]，正確網址如下：
https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload={"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual","entry","officePosting"],"useDate":1,"dateType":"index","dateStartTime":1200,"dateEndTime":1644,"dynStart":null,"dynEnd":null,"useXy":1,"start":1,"list":10}
- 備註：["dateType":"index","dateStartTime":1200,"dateEndTime":1644]是指數年查詢，但["useXy":1]的設定較為高階，會找到指數年查詢以外的資料計入，修改["useXy":0]就可以看出明確的效果。
https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload={"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual","entry","officePosting"],"useDate":1,"dateType":"index","dateStartTime":1200,"dateEndTime":1644,"dynStart":null,"dynEnd":null,"useXy":0,"start":1,"list":10}

以上回覆，提供測試與參考。

**Comment by sudoghut** [comment]
太感謝了！我已經對 API 文檔進行了對應的更新。

還有兩個問題想要請教：

1. 在[「查找入仕途徑為科舉：進士（籠統）且入仕年介於 金朝 到 清朝 的所有人物。返回第 1-10 筆結果」](https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#%E6%9F%A5%E8%A9%A2%E7%A4%BA%E4%BE%8B-by-post-2)中

我從一個可以用的 query （宋代進士）作為起點來修改：

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1368,"dynStart":null,"dynEnd":null,"dateEndTime":1644,"useXy":1,"start":1,"list":10}
```

首先，我試著把 dateStartTime 和  dateEndTime 改成 null, 朝代改成 dynStart":17,"dynEnd":20, 系統會報錯。

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":null,"dynStart":17,"dynEnd":20,"dateEndTime":null,"useXy":1,"start":1,"list":10}
```

接下來，我把查詢改成金代的朝代加上金代的西元年。它可以運作：

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1115,"dynStart":17,"dynEnd":17,"dateEndTime":1234,"useXy":1,"start":1,"list":10}
```

接下來，我把它改成從金代到清代朝代和西元年。它會返回空白：

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1115,"dynStart":17,"dynEnd":20,"dateEndTime":1911,"useXy":1,"start":1,"list":10}
```

我也試著把 useDate 改成 0. 以及把 date 改成 null 也還是不行：

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":0,"dateType":"entry","dateStartTime":1115,"dynStart":17,"dynEnd":20,"dateEndTime":1911,"useXy":1,"start":1,"list":10}
```

```
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":0,"dateType":"entry","dateStartTime":null,"dynStart":17,"dynEnd":20,"dateEndTime":null,"useXy":1,"start":1,"list":10}
```

這個查詢我們希望 date 和 dyn 可以相互獨立查詢。即抑或用 date 只設置西元年查詢，抑或用 dyn 只設置朝代代碼查詢。反而用不著 date 和 dyn 一起查詢。麻煩啦~

2. 關於「[十三、通過地區查詢](https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#%E5%8D%81%E4%B8%89%E9%80%9A%E9%81%8E%E5%9C%B0%E5%8D%80%E6%9F%A5%E8%A9%A2)」。我推測當前 useXy 和時間查詢（dyn 和 date）在程式裡面可能是或然（or）關係。所以才會出現

```
https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload={"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual","entry","officePosting"],"useDate":1,"dateType":"index","dateStartTime":1200,"dateEndTime":1644,"dynStart":null,"dynEnd":null,"useXy":1,"start":1,"list":10}
```

查詢到 1200-1644 以外人物的結果。

對於這裡的邏輯，我們希望是並列（and）關係。即需要同時滿足 useXy 和時間查詢（dyn 和 date）的結果才會顯示。辛苦啦~

**Comment by s8714081** [comment]
第一個問題，在「查找入仕途徑為科舉：進士（籠統）且入仕年介於 金朝 到 清朝 的所有人物。」請參考以下回覆。

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

初始行為：我從一個可以用的 query （宋代進士）作為起點來修改：
/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1368,"dynStart":null,"dynEnd":null,"dateEndTime":1644,"useXy":1,"start":1,"list":10}

ANS：OK

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

首先，我試著把 dateStartTime 和 dateEndTime 改成 null, 朝代改成 dynStart":17,"dynEnd":20, 系統會報錯。
https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":null,"dynStart":17,"dynEnd":20,"dateEndTime":null,"useXy":1,"start":1,"list":10}

請修改"dateType":"dynasty"：

https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"dynasty","dateStartTime":null,"dynStart":17,"dynEnd":20,"dateEndTime":null,"useXy":1,"start":1,"list":10}

ANS：這邊要說明，API文件中提到，注：當 dateType 取值為 entry 或 index 時，僅考慮 dateStartTime 與 dateEndTime 兩個字段的值，不考慮 dynStart 與 dynEnd 的取值。

上述錯誤是因為"dateType":"entry"沒有切換，當"dateType":"entry"時，dateStartTime 與 dateEndTime 是必填欄位。

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

接下來，我把查詢改成金代的朝代加上金代的西元年。它可以運作：

https://input.cbdb.fas.harvard.edu/api/query_entry_postings?RequestPayload={"entry":[36],"usePeoplePlace":0,"peoplePlace":[],"locationType":"peAddr","useDate":1,"dateType":"entry","dateStartTime":1115,"dynStart":17,"dynEnd":17,"dateEndTime":1234,"useXy":1,"start":1,"list":10}

ANS：補充說明，這邊應由前端控制"dateType":"entry"的值，切換 entry 為入仕年 index 為指數年 dynasty 為朝代，會取得對應的參數，提供不同的資料。

當"dateType":"entry"沒有更動時，不會使用 dynStart 與 dynEnd 的取值。

這一段邏輯的程式碼如下，他會先判斷useDate是否要使用，當useDate等於0時，相關參數都不使用，當useDate等於1時，判別dateType的類型，取用相關的參數做查詢。

        if($useDate) {
            if($dateType == 'entry') {
                if(empty($dateStartTime) || empty($dateEndTime)) { return 'Plaese check dateStartTime and dateEndTime have value.'; }
                $row->where('ENTRY_DATA.c_year', '>=', $dateStartTime);
                $row->where('ENTRY_DATA.c_year', '<=', $dateEndTime);
            }
            elseif($dateType == 'index') {
                if(empty($dateStartTime) || empty($dateEndTime)) { return 'Plaese check dateStartTime and dateEndTime have value.'; }
                $row->where('BIOG_MAIN.c_index_year', '>=', $dateStartTime);
                $row->where('BIOG_MAIN.c_index_year', '<=', $dateEndTime);
            }
            elseif($dateType == 'dynasty') {
                if(empty($dynStart) || empty($dynEnd)) { return 'Plaese check dynStart and dynEnd have value.'; }
                $row->join('DYNASTIES', 'BIOG_MAIN.c_dy', '=', 'DYNASTIES.c_dy');
                $row->where('DYNASTIES.c_dy', '>=', $dynStart);
                $row->where('DYNASTIES.c_dy', '<=', $dynEnd);
            }
            else {}
        }


綜上所述，date 和 dyn 可以相互獨立查詢，需要由dateType控制，date 和 dyn 目前不會一起查詢，已經符合需求。

我更新了程式，在API後端判斷，依據dateType，需要提供對應參數的值，如果沒有提供，會回傳提示訊息。

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

第二個問題，謝謝宏甦經理指正，我修改了程式邏輯，需要同時滿足 useXy 和時間查詢（dyn 和 date）的結果才會顯示。

測試範例：

https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload={"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual"],"useDate":1,"dateType":"index","dateStartTime":1238,"dateEndTime":1238,"dynStart":null,"dynEnd":null,"useXy":0,"start":1,"list":10}

https://input.cbdb.fas.harvard.edu/api/query_place?RequestPayload={"peoplePlace":[2928,10522,12553,13947,13949],"placeType":["individual"],"useDate":1,"dateType":"index","dateStartTime":1238,"dateEndTime":1238,"dynStart":null,"dynEnd":null,"useXy":1,"start":1,"list":10}
