### ISSUE TITLE
成對社會係當前是簡化字

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#225]
![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/032bfd67-76be-4b36-8479-44c9e8ee13be)
當前親屬關係界面中成對社會關係資訊仍然是簡化字，還想拜託把它改成正體/繁體。麻煩啦

**Comment by s8714081** [comment]
20230614成對社會關係簡化字修改完成，程式已經更新至issues225-patch1，申請合併至develop，謝謝您。
