### ISSUE TITLE
外文姓名和外文xingming希望能被檢索到

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#227]
## 外文姓名和外文xingming希望能被檢索到

中國歷代人物傳記資料庫當前在收集一篇傳教士的資訊。未來還會系統收錄更多。在工作中我們會發現有些人物的中文名很隨意，常常會希望用他們的外文姓名：

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/61ee4cc1-fc4d-4c46-833e-64cacdb0bb06)

在檢索頁面中：

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/d2597344-bbf2-48be-8b9e-72af13667c20)

搜尋人物：

https://input.cbdb.fas.harvard.edu/basicinformation/571568/edit

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/eb2097f7-4819-46bf-85d4-782344603d86)

## 外文全名

外文全名對應的是 BIOG_MAIN 的 c_name_proper 欄位。它是外文名在原來語言下的寫法。這個欄位當前系統是自動生成，也希望拜託建安在自動生成的時候改成先名後姓：c_mingzi_proper + c_surname_proper，並且把這個欄位開放成可以編輯，以防有一些來自先姓后名的人物被錯誤生成（比如日韓人物的原語言姓名）。

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/9775e0b8-96b9-4b49-9a6c-eda50fa99c88)

## 外文XingMing

外文XingMing 對應的欄位是 BIOG_MAIN 的 c_name_rm. 它是外文名的羅馬字轉寫。這個欄位同意也希望和上段「外文全名」條一樣，自動生成的時候改成先名後姓：c_mingzi_rm + c_surname_rm. 羅馬字的順序我們可以就遵循羅馬字（西方世界）的文化。先名後姓，所以不用開放成可編輯欄位。

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/6aedebf2-b501-4407-a523-5c8fcb55d708)

## 標籤修改

另外還想拜託修改如下標籤：
外文羅馬字轉寫姓
外文羅馬字轉寫名
姓名(拼音)
外文羅馬字轉寫姓名

原始標籤:

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/71239f46-df49-40b2-838b-f4e9d8a7971a)

改動之後的標籤:

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/515aff16-f728-4e94-84c2-46c29b4ae8c2)

感謝！

**Comment by s8714081** [comment]
完成[外文姓名和外文xingming（外文羅馬字轉寫姓名）能被檢索]，
並增加[外文姓]、[外文名]、[外文羅馬字轉寫姓]、[外文羅馬字轉寫名]均可以被檢索，
如需移除這4欄檢索，維持全名的精準查詢，請跟我說，我再遮除這4欄檢索，謝謝。
