### ISSUE TITLE
自動生成拼音

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#228]
## 基本功能

最近我們收到許多 crowdsourcing inputters 的建議，希望 CBDB 可以自動拼音

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/f214a82a-ed8f-4fcd-9b47-718c13a0b124)

還想拜託是否會方便在這裡添加一個「生成拼音」按鈕，讓它自動生成右邊 Xing 和 Ming的拼音呢？

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/7f45c4cc-0d11-4a65-8cd4-0b745125add0)

姓名的拼寫是：姓和名首字母大寫，名字中間不需要添加空格。譬如：

王安石的拼音是 Wang Anshi

## 姓氏拼音

漢字的多音字容易讓自動生成拼音相關的程式 package 犯錯。這裡是 CBDB 整理的姓氏轉拼音列表：

[basic.csv](https://github.com/cbdb-project/cbdb-online-main-server/files/11841871/basic.csv)

希望在程式設計中轉姓氏拼音時優先使用這個 mapping table 來轉換拼音。如果不在這個 mapping table 裡面，再用程式自動轉拼音。

名字部分則自動讓程式轉。

**Comment by s8714081** [comment]
完成[自動生成拼音功能]，製作[Pinyin物件]，提供給CBDB錄入系統專屬使用，
先以提供的指定csv，以[Pinyin資料表]匯入資料庫，
[自動生成拼音功能]會優先查詢[Pinyin資料表]提供指定拼音（第一順位），
再查詢[Pinyin物件]提供拼音（第二順位）。

**Comment by sudoghut** [comment]
感謝！CBDB 資料庫當前用大寫表示 CBDB 的資料表，用小寫表示支持系統運作的資料表。還想拜託把 Pinyin 表的表名在程式中改成小寫字母: pinyin. 完成修改之後我再修改後台的表名。辛苦啦！

**Comment by sudoghut** [comment]
當前可以自動生成拼音，因此在新建人名時希望移除要求輸入拼音的輸入框：

https://input.cbdb.fas.harvard.edu/basicinformation/create

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/04504363-5439-4667-9ac6-e21081d43944)

另外，是否容易在新建人名頁面點擊 submit 轉入基本資料頁面時，自動 trigger 「生成拼音」按鈕。這樣錄入者可以在新建人名的時候不用點擊這個按鈕。需要注意的地方是，一定希望透過 document.referrer 或者類似的方法確保在新建人名之後加載基本資料頁面時才會自動生成拼音，而不是在任何時候打開基本資料頁面都自動生成拼音。因為有時候名字的拼音我們可能會希望保存手動修改後的拼音。

感謝！

**Comment by sudoghut** [comment]
錄入者如果刪除姓之後，希望也能自動清空拼音中的姓

**Comment by s8714081** [comment]
a.Pinyin表的表名改成小寫pinyin。（ＯＫ）
b.新建人名界面的一些改動，以及新建人名時候自動 trigger「生成拼音」按鈕。
　I.從create表單建立資料時，移除姓名(拼音)輸入框的強制填寫。（ＯＫ）
　II.create表單建立資料後，跳轉到edit表單時，自動觸發「生成拼音」，自動填寫。（討論）
　(討論方案：create表單不動，針對三個字的姓名，自動拆解第一個字是姓氏，第二與第三個字是名子，自動填入[姓]、[名]、[Xing]、[Ming]這四個欄位。) 
　III.確保在新建人名之後加載基本資料頁面時才會自動生成拼音，而不是在任何時候打開基本資料頁面都自動生成拼音。（ＯＫ）
c.網頁離開或關閉前的判斷功能，檢查名和Ming是否為空，使用alert的訊息提示。（ＯＫ）
　這裡需要使用js的onbeforeunload狀態（離開或關閉此網頁），近年因為瀏覽器的限制，使用onbeforeunload後，不能再使用alert，而且小視窗的訊息由瀏覽器內建，我們不能修改小視窗的訊息，所以alert需改為使用HTML的訊息提示。
d.錄入者如果刪除姓之後，按下「生成拼音」，同時也能自動清空拼音中的姓。（ＯＫ）
　(優化「生成拼音」的功能，如果取得資料為空白，也要能正確處理。)

2.討論後將實作b.II的方案：
a.首先，我們現在有 pinyin 表，其實這就是 CBDB 的常見漢人姓氏表。未來我們也可以把滿人、蒙古人的姓一點一點整理補充進去；
b.第二，如果用 pinyin 表來拆姓氏，首先在程式裡面要對 pinyin 表進行 sort，讓它從長到短排序。（ＯＫ程式有做到）
　我們希望優先用司馬（更長的字串）來切姓氏，而不是司*
　負責錄入的學者或者同學根據需要自己的判斷來決定是否要手動拆姓名，或者這個人物就是沒有姓氏*
c.第三，如果是切出來單字姓，那麼剩下部分的字長必須是小於等於二。比如馬嘎爾尼，切出來姓氏是馬之後，len(嘎爾尼)>2，所以就不切這樣的姓名。（ＯＫ程式有做到，剩下部分的字長必須是小於等於二。）
　當然，這會帶來一個問題，比如馬斯克（Elon Musk）就會被切成姓馬。但這種就交給錄入者來處理吧。
d.第四，如果切出來多字的姓氏（長孫，司馬，公孫...，未來我們加入其他民族姓氏的時候，也會有比如愛新覺羅、瓜爾佳，甚至海外的姓氏，比如彼得，喬治等等），剩下部分的字長不做限制。比如司徒雷登，如果切成司徒|雷登，也不算錯。
e.第五，以上情況以外的所有情況都把整個姓名放到名字裡面，姓留空，並且自動生成拼音。負責錄入的學者或者同學根據需要自己覺得是否這個人物就是沒有姓氏，或者應該手動切割姓名。（ＯＫ程式有做到）

**Comment by sudoghut** [comment]
感謝！經過輸入的測試，會希望把拼音「姓名（拼音）」直接從新建人物的窗體中刪除（只留下 person_id 和 姓名（中）。麻煩考慮。原因如下：

https://input.cbdb.fas.harvard.edu/basicinformation/create

<img width="1193" alt="image" src="https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/bd3e207b-0cfb-4253-acf9-fb2720da8ccd">


一方面，當前自動創建拼音的功能已經非常好用。另一方面，在錄入者填入「姓名（拼音）」的內容有 space 的時候，其實已經切分了姓氏和名字的拼音，譬如 Qiaozhi Huashengdun:

<img width="672" alt="image" src="https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/1ce3d9e4-46f3-4ffc-ae91-61822baf6993">

在轉入基本資料的時候，會變成 Qiaozhihuashengdun:

<img width="1085" alt="image" src="https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/c7f6c538-4a93-4db0-8e44-622a6e37f965">

錄入者需要再把 Qiaozhihuashengdun 改成 Qiaozhi Huashengdun. 如果我們自動根據 space 來切姓名的拼音，那麼中文部分並沒有空格，那麼中文姓名的部分如果按照拼音來自動切分，邏輯就非常麻煩，也容易出錯。

如果直接把「姓名（拼音）」input box 在創建人物的時候刪除，能簡化工作邏輯，更加智能。

**Comment by s8714081** [comment]
git commit -m '20230629新建人物刪除[姓名(拼音)]輸入欄位，使用自動生成拼音。'
更新至GitHub的issues228-patch2分支，申請合併至develop，謝謝。
