### ISSUE TITLE
離開頁面時姓名是否為空的自動判斷

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#229]
## 基本功能

當前，錄入者新增一個人物：

https://input.cbdb.fas.harvard.edu/basicinformation/create

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/e067107c-92d6-46a3-bc03-9c462b99923e)

之後，如果 ta 直接關閉頁面，那麼這個人物會被添加進資料庫，且姓、名和姓、名的拼音會為空。為了避免姓名為空，當前程式在點  Submit 的時候，會自動判斷「名」和 「Ming」這兩個欄位是否為空：

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/1bfacdb1-b6d2-4726-8a3c-3a9cc173980a)

希望能把這個判斷也引入關閉頁面行為中。**如果用戶要離開頁面時「名」和「Ming」為空，系統會要求錄入者填上「名」和「Ming」(因為有些民族沒有姓氏，所以姓氏為空不需要報錯)**.

## 「姓不能为空」改為「名不能为空」

在上方截圖中報錯的信息為「姓不能为空」，而實際應當是「名不能为空」。

## 按鈕的兩個小改動

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/4daed566-b4a7-4f86-af0a-a02138bd0f90)

- 希望 create 和 delete 兩個按鈕的首字母都大寫：Create 變成 Delete

- Create 功能有時候容易被誤觸，它的使用頻率遠遠低於 Submit. 所以希望能把 Create 按鈕移到右側 Delete 的旁邊（左 Create, 右 Delete）

**Comment by s8714081** [comment]
完成[離開頁面時姓名是否為空的自動判斷]提示訊息文字修改，版面配置移動完成。

**Comment by sudoghut** [comment]
希望在關閉頁面的時候，可以檢查姓和 xing 是否為空。如果為空，希望有一個 alert 來提示 名不能為空 or/and Ming不能為空

**Comment by s8714081** [comment]
網頁離開或關閉前的判斷功能，檢查名和Ming是否為空，使用alert的訊息提示。（ＯＫ）
[這裡需要使用js的onbeforeunload狀態（離開或關閉此網頁），近年因為瀏覽器的限制，使用onbeforeunload後，不能再使用alert，而且小視窗的訊息由瀏覽器內建，我們不能修改小視窗的訊息，所以alert需改為使用HTML的訊息提示。] 
![離開視窗時未填寫 名 和 Ming 的提示訊息](https://github.com/cbdb-project/cbdb-online-main-server/assets/6869447/a8c1e5e3-f769-4f98-9e3d-d3f86efe3c5f)
