### ISSUE TITLE
query_assoc_network API query

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#234]
https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#%E5%8D%81%E4%B8%89%E6%9F%A5%E8%A9%A2%E7%A4%BE%E6%9C%83%E9%97%9C%E4%BF%82%E7%B6%B2%E8%B7%AF

**Comment by s8714081** [comment]
「查詢社會關係網路API」初版製作完成，請參考下列說明。

正確的API查詢語句：
/api/query_assoc_network?RequestPayload={"people":[1762,3767],"assocCode":[280],"assocType":["02"],"maxNodeDist":1,"place":[13305],"usePeoplePlace":1,"broad":0,"useDy":1,"dynStart":15,"dynEnd":15,"includeMale":1,"includeFemale":1}
請協助修正「[https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#十三查詢社會關係網路」的「查詢示例」。

符合 assocType 為 02 的所有 c_assoc_code，查詢方法驗證程式邏輯，請參考附加圖檔。
![經由ASSOC_TYPES c_assoc_type_parent_id='02'查得ASSOC_TYPES c_assoc_type_id](https://github.com/cbdb-project/cbdb-online-main-server/assets/6869447/b34c2302-652c-4fe8-be26-92fdebca7855)
![經由ASSOC_CODE_TYPE_REL c_assoc_type_id查得ASSOC_CODE_TYPE_REL c_assoc_code](https://github.com/cbdb-project/cbdb-online-main-server/assets/6869447/caee7e4f-15d3-4929-b2f3-8a0b075211da)

當 maxNodeDist 為 0 時，查詢 people（本例中為 "people":[1762, 3767]）中相互的社會網路關係，即 ASSOC_DATA 中 c_personid 與 c_assoc_id 均为 people（本例中為 "people":[1762, 3767]）陣列裡的 id. 來自使用者的地址、時間、性別等查詢條件均有效。

當 maxNodeDist 為 2 時，首先查詢方式和 maxNodeDist = 1 相同。在獲得的 maxNodeDist = 1 查詢結果中，將 ASSOC_DATA.c_assoc_id 作為 ASSOC_DATA.personid, 再進行一次 maxNodeDist = 1 查詢。

當 maxNodeDist 大於 2 時，返回：「API 暫不支援 maxNodeDist 大於 2 之查詢」。
API 暫不支援 maxNodeDist 大於 2 之查詢
![API 暫不支援 maxNodeDist 大於 2 之查詢](https://github.com/cbdb-project/cbdb-online-main-server/assets/6869447/60e65d19-5f9d-4398-82ef-51da8597ddc2)

輸出格式：
{"pId":"1493","pName":"Su Zhe","pNameChn":"蘇轍","aId":"3257","aName":"Liu Ju(2)","aNameChn":"劉巨","pIndexYear":"1039","pSex":"M","aIndexYear":"","aSex":"M","pAddrID":"13305","pAddrName":"Meishan","pAddrNameChn":"眉山","pX":"103.831459","pY":"30.050497","aAddrID":"13305","aAddrName":"Meishan","aAddrNameChn":"眉山","aX":"103.831459","aY":"30.050497","pAssocRelationId":"22", "pAssocRelation":"Student of","pAssocRelationChn":"為Y之學生","distance":"0","count":1}
已經符合需求。

以上回報，申請合併至develop，並測試是否符合需求，謝謝您。

**Comment by sudoghut** [comment]
@sudoghut Hongsu will test it in one week

**Comment by sudoghut** [comment]
Hongsu will add the primary key fields in ASSOC_DATA to the output file

**Comment by sudoghut** [comment]
Jianan will be back on December

**Comment by angelateng** [comment]
依照API.md定義的[過濾條件](https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#%E9%81%8E%E6%BF%BE%E6%A2%9D%E4%BB%B6%E7%82%BA-or-%E9%80%A3%E6%8E%A5%E7%9A%84%E4%B8%89%E5%80%8B%E6%A2%9D%E4%BB%B6)，將取出的資料進行過濾。
請測試是否符合需求，若符合請將issues234-patch3合併至develop，謝謝您。

**Comment by angelateng** [comment]
20230825 push 分支 issue234-patch4：
查詢社會關係網路API，修改過濾地點條件：
當 $usePeoplePlace &&  $maxNodeDist == 0 時，人物和關係人都符合 URL 上的 $people ，不論是否符合 $usePeoplePlace 。
當 $usePeoplePlace &&  $maxNodeDist >= 1時，分為4種狀況：
1. 只要此人物和關係人都符合 URL 上的 $people ，即放入結果，不論是否符合 $usePeoplePlace  （和 $maxNodeDist == 0 時相同）
2. 如果此人物是 URL 上的 $people 之一，關係人不是 URL 上的 $people 之一；但關係人在 Biog_Main 上的 c_index_addr_id 符合 $usePeoplePlace ，亦放入結果
3. 如果關係人是 URL 上的 $people 之一，此人物不是 URL 上的 $people 之一；但此人物在 Biog_Main 上的 c_index_addr_id 符合 $usePeoplePlace ，亦放入結果
4. 如果關係人和關係人都不在 $people 中，若雙方在 Biog_Main 上的 c_index_addr_id 都符合 $usePeoplePlace ，亦放入結果

另外 issues240 關於 ALTNAME_DATA.c_sequence 新增欄位，已完成下列兩項功能，也一併更新在此分支
1. 在「別名」頁面中以 c_sequence 欄位來排序
2. 在「別名」的「新增」和「edit」按鈕觸發的頁面中，增加對應欄位

以上回報，申請合併至develop，並測試是否符合需求，謝謝您。

**Comment by angelateng** [comment]
推送分支 issues234-patch5 ：本次修改 $maxNodeDist == 1 和 $maxNodeDist == 2的邏輯。
當maxNodeDist":1 時，先找出所有與url上的people有直接關係的c_assoc_id，將所有人物合併去重之後，以此人物清單為範圍，找出彼此之間的所有社會關係。
當maxNodeDist":2 時，以maxNodeDist":1 回傳的c_assoc_id 作為 ASSOC_DATA.personid， 再進行一次查詢，將所有人物合併去重之後，以此人物清單為範圍，找出彼此之間的所有社會關係。
以上回報，請檢視是否合於需求，謝謝。

**Comment by angelateng** [comment]
推送分支 issues234-patch6 ：
1. 人物和關係人都同是需受朝代條件限制
2. useXy會以URL上的place做xy軸擴展，並限制人物和關係人的c_index_addr_id要在此擴展後的place陣列中。如果usePeoplePlace==1，那麼會依照擴大後的place陣列做邏輯判斷，而非只是URL上的place。
3. 人物和關係人都會受到includeMale和includeFemale的限制

以上回報，但還暫時不能merge into develop，因為需要debug。

**Comment by angelateng** [comment]
推送分支 issues234-patch6 ：

1. 人物和關係人都同是需受時間條件限制（useDy和indexYear），且URL上的dynStart、dynEnd；人物與關係人在Biog_Main中的c_dy，都會先轉成Dynasty.c_sort，再進行過濾。
2. useXy會以URL上的place做xy軸擴展，並限制人物和關係人的c_index_addr_id要在此擴展後的place陣列中。如果usePeoplePlace==1，那麼會依照擴大後的place陣列做邏輯判斷，而非只是URL上的place。
3. 人物和關係人都會受到includeMale和includeFemale的限制


以上回報，申請合併至develop，並測試是否符合需求，謝謝您。

**Comment by angelateng** [comment]
推送 issues234-patch7，並發出pull request。
本次修改的地方：
增加了一個function filter_conditions來統整所有過濾條件（地方 usePeoplePlace, useXy, 時間 indexYear, useDy, 性別 includeMale, includeFemale） 的邏輯：
1. 若兩方都在URL people上，兩方都不受條件限制
2. 若人物在URL people上，關係人要滿足所有條件
3. 若關係人在URL people上，人物要滿足所有條件
4. 若兩方都不在URL people上，兩方都要滿足所有條件
