### ISSUE TITLE
The function of the c_sequence column in ALTNAME_DATA

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#240]
在 ALTNAME_DATA 表中增加了新欄位 c_sequence，欄位類型為 smallint(6)

拜託在程式中實現的功能有兩個：

1. 在「別名」頁面中以 c_sequence 欄位來排序：

https://input.cbdb.fas.harvard.edu/basicinformation/1762/altnames

排序規則為：先按照（有 value 的） c_sequence 從小到大排序，之後再放 c_sequence 為 null 的記錄

2. 在「別名」的「新增」和「edit」按鈕觸發的頁面中

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/2a426d41-b060-4cd6-8c7b-452d872f238b)

增加「次序(c_sequence)」input box，對應 ALTNAME_DATA.c_sequence 欄位:

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/6bf9b7b1-cedd-4660-b2d8-314b1642af0e)

這個 input box 只允許輸入數字，或者留空。

麻煩了！感謝！

**Comment by angelateng** [comment]
一併更新在 issues234-patch4
