### ISSUE TITLE
各地址選單中的多個歸屬問題

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#246]
當前錄入系統中 ID 為 12757 的會稽有一條記錄（比如，這是在「地址」界面中的一個例子）：

起止年為 960-1279 的會稽（12757）歸屬地為 12754 越州

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/48afc343-0d2b-4372-befc-72fd0cb0c75c)

而在後台中，會稽的資訊是這樣的：

ADDR_CODES 表中：會稽（12757） 960-1279 （沒問題）

https://input.cbdb.fas.harvard.edu/addrcodes/12757/edit

在 ADDR_BELONGS_DATA 表中，12757 會稽有兩條歸屬資訊：

一條是 960-1130 年，會稽歸屬越州（12754）（這條記錄為顯示在地址查詢介面中的記錄）

https://input.cbdb.fas.harvard.edu/addrbelongsdata/12757-12754-960-1130/edit

另一條是 1131-1279 年，會稽歸屬紹興府（101094）（這條記錄實際存在，但是沒有顯示）

https://input.cbdb.fas.harvard.edu/addrbelongsdata/12757-101094-1131-1279/edit

因此，對於學者來說希望看到的是兩條歸屬地都可以顯示，即：

- 12757 Kuaiji 會稽 960-1279 [[12754 越州 960-1130]]
- 12757 Kuaiji 會稽 960-1279 [[101094 紹興府 1131-1279]]

兩條記錄。上層地址（越州和紹興府）的時間都用它們的 ID 對應在 ADDR_CODES 裡面查到的 c_firstyear 和 c_lastyear.

麻煩啦！

**Comment by angelateng** [comment]
已經修改輸入選單，當有多筆上層資訊時會顯示多個選項。
<img width="514" alt="未命名2" src="https://github.com/cbdb-project/cbdb-online-main-server/assets/19771988/2b22c519-6e1a-4b83-a604-56382f5c94cc">

然而使用者按下儲存時，因為BIOG_ADDR_DATA並沒有c_belongs_to欄位，所以在下次進入編輯畫面時，input欄位只會出現第一筆c_belongs_to，其他上層歸屬資訊將以純文字方式附註在輸入欄位底下。
<img width="475" alt="未命名" src="https://github.com/cbdb-project/cbdb-online-main-server/assets/19771988/251635bd-ba01-48fb-9e6d-98e78d1853bf">

請檢視是否合於需求。我將發出 pull request，請求將issue246-patch1 merge into develop，謝謝。
