### ISSUE TITLE
在基本資料下修改朝代信息報錯（寫 operation 表的問題）

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#25]
在基本資料下，譬如這個人物：
http://162.105.134.121:22222/basicinformation/439711

如果我把朝代從空白改為“清”，系統會報錯如下：

![image](https://user-images.githubusercontent.com/8538710/51387585-8c3b8780-1b61-11e9-963f-771efc8cd075.png)

從報錯信息是上，是 insert operation 表記錄當前操作的時候 resource_id 為 null

麻煩啦

**Comment by s8714081** [comment]
從錯誤訊息追蹤，先檢查程式對於operation資料表寫入的部分。
修改BiogMainRepository.php:154行即可，
原程式：(new OperationRepository())->store(Auth::id(), $id, 3, 'BIOG_MAIN', $biogbasicinformation->tts_sysno, $data);
原使用$biogbasicinformation->tts_sysno，
修改為$biogbasicinformation->c_personid。
