### ISSUE TITLE
刪除 tts_sysno 欄位

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#259]
我們決定在後台刪除各表的 tts_sysno 欄位之後，發現系統一下功能都會報錯

https://input.cbdb.fas.harvard.edu/basicinformation/1762/altnames
https://input.cbdb.fas.harvard.edu/basicinformation/1762/texts
https://input.cbdb.fas.harvard.edu/basicinformation/1762/offices
https://input.cbdb.fas.harvard.edu/basicinformation/1762/entries
https://input.cbdb.fas.harvard.edu/basicinformation/1762/events
https://input.cbdb.fas.harvard.edu/basicinformation/1762/statuses
https://input.cbdb.fas.harvard.edu/basicinformation/1762/kinship
https://input.cbdb.fas.harvard.edu/basicinformation/1762/assoc

麻煩建安啦！

**Comment by s8714081** [comment]
資料庫刪除 tts_sysno 欄位，程式在之前已經陸續捨棄 tts_sysno 欄位值的使用，雖未使用，但延續著之前的程式脈絡，依舊有儲存 tts_sysno 欄位值，本次資料庫刪除 tts_sysno 欄位，將相關程式儲存 tts_sysno 欄位值的行為移除，恢復相關頁面增刪改查（CRUD）的功能正常。
