### ISSUE TITLE
altname sequence = 0 issue

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#261]
我們發現了一個小 bug，還想拜託幫忙。如果在人物的別名中記錄，我們記錄了 sequence 為 0，那麼點擊這個人物的時候就會報錯：

https://input.cbdb.fas.harvard.edu/basicinformation/331410/altnames

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/4de2826b-88de-4316-b2e8-20194ed4d638)

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/ea5b485d-c2e5-4fa3-a3bd-f5cd946fa002)

我觀察到兩件事：

1. 報錯的資訊提示 c_source，但其實是 c_sequence 欄位的問題。
2. 出錯的連結為：https://input.cbdb.fas.harvard.edu/basicinformation/331410/altnames/331410-NULL-%E4%BA%8C%E7%BF%9F-0/edit
在 .../331410-NULL-... 這部分的  NULL 實際上是 sequence number. 這時候如果我們把它修改成 0，頁面就能打開了：
https://input.cbdb.fas.harvard.edu/basicinformation/331410/altnames/331410-0-%E4%BA%8C%E7%BF%9F-0/edit

麻煩啦！感謝！

**Comment by s8714081** [comment]
修正altnames index對於c_sequence的判斷，c_sequence的資料有NULL、0、1-7。

申請合併至develop，謝謝。
