### ISSUE TITLE
Modify the "create" Function in Basic Information Page

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#265]
我們收到來自北大編輯小組基於工作經驗對「基本資料」頁面中 「Create」按鈕（如圖）功能修改的建議。

https://input.cbdb.fas.harvard.edu/basicinformation/1762/edit

![image](https://github.com/cbdb-project/cbdb-online-main-server/assets/8538710/e463e8eb-aada-4258-85c6-7b7e147d8f4c)

於是希望對 Create 按鈕做如下調整，還想拜託評估。

1. 把 Create 按鈕分成兩個按鈕：一個是「Duplicate Basic Info」，一個是「Duplicate Collateral Info 」。
2. 關於這兩個按鈕的功能：

    - 在功能上，「Duplicate Basic Info」按鈕和原來的 Create 功能相同，即用當前人物的「基本信息」建立一個新人物。
    - 在功能上， 「Duplicate Collateral Info」除了原來 Create 的功能以外，編輯小組還希望能為同輩人物（兄弟姐妹）複製以下信息：地址，出處，親屬，社會關係，社會機構，社會區分。這六種資訊已經和北大小組確認無誤。

3. 以下是「Duplicate Collateral Info」按鈕基於 c_personid 進行資訊複製+新建人物涉及到六種資訊對應的資料表：
    - 地址 BIOG_ADDR_DATA
    - 出處  BIOG_SOURCE_DATA
    - 親屬 KIN_DATA. 特別需要小心，在這裡除了以 c_personid 複製親屬關係以外，還要透過 c_kin_id 複製成對的親屬關係。（例如 A 是 B 的父親，B 是 A 的孩子。親屬關係需要成對複製）
    - 社會關係 ASSOC_DATA. 特別需要小心：1) 這裡除了以 c_personid 複製社會關係以外，還要透過 c_assoc_id 複製成對的社會關係。（例如 A 是 B 的老師，B 是 A 的學生。社會關係需要成對複製）。2) ASSOC_DATA 設計人物關係的欄位還有 c_kin_id, c_kin_code, c_assoc_kin_id, c_assoc_kin_code, c_tertiary_personid, c_tertiary_type_notes. 這些欄位資訊的內容比較複雜。我建議在複製的時候，把這些欄位的值設置為 0 或者 null(c_tertiary_type_notes 是 text 欄位，所以建議只有這個欄位設置為 null)。如果我們的編輯小組需要，拜託他們手動添加。
    - 社會機構 BIOG_INST_DATA
    - 社會區分 STATUS_DATA

**Comment by s8714081** [comment]
1.依據需求github issues 265，製作「Duplicate Collateral Info 」功能。
2.按鍵功能需要創建人物的六種對應資訊
＊地址 BIOG_ADDR_DATA
＊出處 BIOG_SOURCE_DATA
＊親屬 KIN_DATA
　備註：特別需要小心，在這裡除了以 c_personid 複製親屬關係以外，還要透過 c_kin_id 複製成對的親屬關係。（例如 A 是 B 的父親，B 是 A 的孩子。親屬關係需要成對複製）
＊社會關係 ASSOC_DATA
　備註：特別需要小心：
　1) 這裡除了以 c_personid 複製社會關係以外，還要透過 c_assoc_id 複製成對的社會關係。（例如 A 是 B 的老師，B 是 A 的學生。社會關係需要成對複製）。
　2) ASSOC_DATA 設計人物關係的欄位還有 c_kin_id, c_kin_code, c_assoc_kin_id, c_assoc_kin_code, c_tertiary_personid, c_tertiary_type_notes. 這些欄位資訊的內容比較複雜。在複製的時候，把這些欄位的值設置為 0 或者 null(c_tertiary_type_notes 是 text 欄位，所以將c_tertiary_type_notes欄位預設值設置為 null。
＊社交機構 BIOG_INST_DATA
＊社會區分 STATUS_DATA
3.逐筆檢測「Duplicate Collateral Info 」功能創建的每一筆資料，在〔最近編輯列表〕的連結功能均有效，連結表單均可以正常編輯。

**Comment by sudoghut** [comment]
https://github.com/cbdb-project/cbdb-online-main-server/pull/266
