### ISSUE TITLE
social association api query

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#278]
This link works if I set `assocType = 05`:
[https://input.cbdb.fas.harvard.edu/api/query_assoc_network?RequestPayload={"people":["131191"],"assocCode":[],"assocType":["05"],"maxNodeDist":1,"place":[13305],"usePeoplePlace":0,"broad":0,"useDy":0,"dynStart":15,"dynEnd":15,"includeMale":1,"includeFemale":1}](https://input.cbdb.fas.harvard.edu/api/query_assoc_network?RequestPayload={"people":["131191"],"assocCode":[],"assocType":["05"],"maxNodeDist":1,"place":[13305],"usePeoplePlace":0,"broad":0,"useDy":0,"dynStart":15,"dynEnd":15,"includeMale":1,"includeFemale":1})

But this link doesn't work when I set `assocType = 0509`:
[https://input.cbdb.fas.harvard.edu/api/query_assoc_network?RequestPayload={"people":["131191"],"assocCode":[],"assocType":["0509"],"maxNodeDist":1,"place":[13305],"usePeoplePlace":0,"broad":0,"useDy":0,"dynStart":15,"dynEnd":15,"includeMale":1,"includeFemale":1}](https://input.cbdb.fas.harvard.edu/api/query_assoc_network?RequestPayload={"people":["131191"],"assocCode":[],"assocType":["0509"],"maxNodeDist":1,"place":[13305],"usePeoplePlace":0,"broad":0,"useDy":0,"dynStart":15,"dynEnd":15,"includeMale":1,"includeFemale":1})

**Comment by s8714081** [comment]
原本[assocType = 05]是查詢ASSOC_TYPES.c_assoc_type_parent_id，增加兼容模式，也可以使用[assocType = 0509]指定查詢ASSOC_TYPES.c_assoc_type_id。
![原本 assocType = 05 是查詢ASSOC_TYPES c_assoc_type_parent_id，增加兼容模式，也可以使用 assocType = 0509 指定查詢ASSOC_TYPES c_assoc_type_id。](https://github.com/user-attachments/assets/df24b5b8-199b-41af-99f0-f26ad688f4ce)
