### ISSUE TITLE
Create book issue

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#285]
在著作編碼表界面下, 如果點擊「新增」：
https://input.cbdb.fas.harvard.edu/textcodes
![image](https://github.com/user-attachments/assets/dbf1eda9-6a23-475f-a17d-3215c003f904)

界面就會變成一片空白：
https://input.cbdb.fas.harvard.edu/textcodes/create
![image](https://github.com/user-attachments/assets/7c615b70-18cc-44cc-a372-edc13352156b)

**Comment by s8714081** [comment]
修正vue語法，進行除錯。
