### ISSUE TITLE
在“親屬”中無法將“親屬關係(c_kin_code)”設定為 -1

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#49]
在任何人物的親屬 tab 中，將“親屬關係(c_kin_code)”設定為 -1（如下圖）
![image](https://user-images.githubusercontent.com/8538710/61208690-931b0f80-a72a-11e9-8beb-7959069c9908.png)

系統將會出錯（如下圖）
![image](https://user-images.githubusercontent.com/8538710/61208958-1dfc0a00-a72b-11e9-8648-c534d8341870.png)

並且用戶無法編輯或者刪除這條記錄，只能從後台刪除。從後台刪除數據的時候，可以發現數據實際上已經寫入了（如下圖）
![image](https://user-images.githubusercontent.com/8538710/61209059-5865a700-a72b-11e9-97d5-5bb62eaed99c.png)

希望能夠：1，保存 c_kin_code=-1 時不出錯。2，錄入進系統的  c_kin_code=-1 相關數據希望能夠被打開、編輯和刪除（當前任何操作都會報錯）。

感謝！

**Comment by s8714081** [comment]
一、CBDB親屬關係(c_kin_code)設定為-1的錯誤修正
1.確認CBDB團隊需求：
  1，保存 c_kin_code=-1 時不出錯。
  2，錄入進系統的 c_kin_code=-1 相關數據希望能夠被打開、編輯和刪除（當前任何操作都會報錯）。
2.檢查相關程式，確認為聯合主鍵的組成如果出現負號，會影響資料的索引。
3.修改聯合主鍵判斷的程式，能夠辨識「28181--1--1」這種類型的資料（第一組為28181，第二組為-1，第三組為-1）。
4.檢查相關的錄入表單，聯合主鍵是否會遇到相同情境（負數），共有：地址、別名、入仕、社會區分、親屬、社會關係。
5.優先修改親屬的錄入表單相關程式，完成需求第一、二項。
6.創建branch issue49，推送至GitHub，git commit -m '20190716修正親屬關係(c_kin_code)設定為-1'。
7.後續進行地址、別名、入仕、社會區分、社會關係等錄入表單的修正。
