### ISSUE TITLE
在线查询系统建制计划

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#55]
![image](https://user-images.githubusercontent.com/8538710/70245290-caa95780-17b0-11ea-904f-f2a9b44622b3.png)

非常感谢北大信管的同学加入 CBDB 在线查询系统开发社区！这是我对开发设计的建议:

1，图中 3 Filter Tools 中 Select Address 信息需要明确：是入仕地址，还是籍贯地址，还是其他地址；图中 3 Filter Tools 中 Select Relationship 信息需要明确，是亲属关系还是社会关系。

2，图中 4 Query Input 如果是面向 code 表的 input，建议基于选择而不接受自由输入；

3，截图是入仕查询，而在图中 4 Query Input 所有选项都是职官查询；

4，建议尽量不要在查询界面上使用 EnName、ChName 这样的缩写，或者在不得不缩写的地方，用悬浮窗说明该栏位的实际意义；

5，图中 7 Result Show 中搜索的栏位会如何设置呢？搜索Name、姓名、Index Year 或者允许用户定义需要搜索的栏位？

6，图中 8 Download Data 我们并不特别建议把 KML 当做默认保存选项，有坐标信息的 CSV 以及 gephi/pajek 格式可以作为默认。

7，图中 8 Download Data，用户有时候会希望导出查询结果的**任官地址**信息，有时候会希望导出**籍贯地址**信息，有时候会希望导出**入仕地址**信息等等。可能需要设置多种信息导出的选项。

**Comment by yanchengxi** [comment]
很高兴认识人家，我来回答一下部分问题：
（1）关于地址和关系的问题，这里我们希望设计一种模式，3中“query condition option”是一类基础功能库，即只提供基础功能的最低层接口（都是一样的），比如地址吧，它提供的具体用户希望获取的地址表的数据，至于籍贯地址，还是其他地址比如迁居地址？做官地址，这个主要在4中体现的，（3点击以后会跳出一个modal界面，里面是地址可以查询和选择的具体内容，select以后的内容将在4中体现；当然用户也可以不使用query condition option， 直接在4中填）。因此4部分每个不同实体或者关系查询是不一样的（不一样的设计），比如官职实体查询页面中需要官职地址（可以看到Office EnPlace就是）或者人的籍贯地址（看到Person EnPlace就是）
（2）这个问题主要是这个图其实还有部分没有呈现，就是（1）里面谈到的，3选择的部分将显示到4里面，这个和现有的access数据库是一样的逻辑，只不过我们重新把这些基础模块整理为一个模块库，便于开发和理解。
（3）这个我们就是举个例子，这个例子有点问题，我们重新弄了一下（不好意思）
（4）嗯嗯，我及时修改，这个意见很重要
（5）是这样的，Result Show用的是bootstrap-table.js的组件，这个组件提供强大的查询功能，点击“九方格”的图标，会弹出一个包含所有table列的checkbox，用户可以自己选择查询列的范围，比如Name或者 Name和Index Year等组合都可以的

（6）嗯嗯，这个我们及时修正
（7）这个问题和Result Show有关，就是说用户需要在Result Show内进行相关查询和操作，确定以后，Download Data会根据Result Show表格中当前的数据进行保存，行或者列（都需要先对Result Show做操作）。
具体的内容会在下次会议上，现场演示，上述的一些问题我们也会修补，希望各位老师和专家多多批评和指正。

**Comment by sudoghut** [comment]
谢谢承希的回复！
关于 1，大概能明白了设计思路。但千万要小心，可以检索的地址信息非常多，包括传记地址、任官地址以外，还有大量其他类型的地址，比如入仕地址、社会关系建立地址、社会机构任职地址等等。
