### ISSUE TITLE
希望可以在出處中增加時間欄位

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#56]
Dear Jianan,

我們在工作中產生了一個需求，希望可以得到您的幫助。
在地址、别名、著述、官名、入仕、事件、社會區分、親屬、社會關係、財產、社交機構、出处界面的“出處”錄入中， 不僅顯示 id + pinyin + 書名 + 分類（如下圖）
 
![image](https://user-images.githubusercontent.com/8538710/70571218-5a4b6d80-1bd8-11ea-9ca7-548bce0e018d.png)

而且希望串接上 text_codes 表中 c_period 欄位的時間資訊（如下圖）
 
![image](https://user-images.githubusercontent.com/8538710/70571259-7222f180-1bd8-11ea-8b4b-3a0f87548715.png)

譬如當前“38828 Chang ping zhou zhi 昌平州志 著作（籠統）/著作（籠統）/古書原文”
希望變成“38828 Chang ping zhou zhi 昌平州志 光緒 著作（籠統）/著作（籠統）/古書原文” 
不知道是否方便呢？感謝！
另外，當前“出处”是简化字，是否方便改成“出處”呢？謝謝~~~
 

Best,

Hongsu

**Comment by s8714081** [comment]
程式已經修改完成了，推送至Github的issue56 branch，申請合併至develop，請群超博士審核，謝謝您^_^
20191211_issue56在出處中增加時間欄位
1.	ApiController.php修改searchText function，輸出增加c_period欄位資訊
2.	當前“出处”是簡化字，修改版型文字為“出處”。
![修改後回報1](https://user-images.githubusercontent.com/6869447/70586088-28023600-1c01-11ea-9fa8-0bb6f6c808ab.PNG)
![修改後回報2](https://user-images.githubusercontent.com/6869447/70586093-29cbf980-1c01-11ea-9638-bb5e3fbbe24d.PNG)
![修改後回報3](https://user-images.githubusercontent.com/6869447/70586097-2d5f8080-1c01-11ea-85c8-e789b3790af6.PNG)
