### ISSUE TITLE
CBDB录入系统的Windows安装步骤

### ISSUE THREAD

**Issue by yanchengxi** [cbdb-project/cbdb-online-main-server#59]
**1. 基础环境搭建**
（1）安装与配置wamp（PHP + MYSQL +APACH），由于Laravel5.5版本要求PHP >= 7.0.0，因此这里选择wamp=3.1.9（PHP=7.2.18）：

- 安装完成后启动，启动成功后，桌面右下角会出现绿色的wamp图标，浏览器访问localhost，能输出wamp信息就是安装成功。

- 配置PHP环境变量，右击计算机-属性-高级系统设置-环境变量-系统变量-双击PATH 加入 php的路径，例如我的路径是D:\Software\Wamp\wamp64\bin\php\php7.1.29，若显示丢失MSVCR110.dll或者MSVCR120.dll：
       缺MSVCR110.dll下载这个：Visual C++ Redistributable for Visual Studio 2012 Update 4（https://www.microsoft.com/zh-CN/download/details.aspx?id=30679）
       缺MSVCR120.dll下载这个：Visual C++ Redistributable Packages for Visual Studio 2013（https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=40784）

- Apache端口配置：确保当前监听端口没有被占用，如果需要修改（默认80端口）例如修改为8888端口，请找到D:\Software\Wamp\wamp64apache\httpd.conf加入：
`Listen [::0]:8888`**

- Mysql配置，建议加入Mysql环境变量，并且使用Navicat导入数据。这里配置Mysql环境变量，例如D:\Software\Wamp\wamp64\bin\mysql\mysql5.7.26\bin；导入数据左侧列表右键选择要导入的数据库 -》运行 SQL 文件 -》选择要执行的 SQL 文件，然后 “开始“（不要直接使用工具/命令列界面导入，否则会报out of memory错误），这里导入的时cbdb_data。

（2）安装Composer，直接将其安装包下载Composer-Setup.exe即可

- 安装过程如果出现如下错误：The openssl extension is required for SSL/TLS protection… ，请查看php否开启了php_openssl扩展，如没开启请开启该扩展再次安装。开启方法：打开php的php.ini配置文件，开启php_openssl.dll扩展（删除前面的分号），然后重启WAMP服务器。

- 注意勾选Developer mode，但安装时可以不要勾选代理。

- 在命令提示符中输入composer -v 不报错即可

**2、植入lavarel项目**
（1）github下载CBDB的录入系统项目，注意下载develop版本，网址请见：https://github.com/cbdb-project/cbdb-online-main-server
（2）复制一个.env.example并命名为.env，修改.env：
APP_NAME= Laravel-CBDB 【你的项目名字（随便起）】
APP_ENV=local
APP_KEY= base64:a4csRNmaaaaaaaaaaaaaaaaaaaaaaa【这里是app的key等会自动生成不用管】
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION= mysql 【选择数据库类型】
DB_HOST=127.0.0.1【数据库ip】
DB_PORT=3306【数据库端口】
DB_DATABASE=cbdb_data【数据库的cbdb数据表】
DB_USERNAME=root【用户名，下面是密码，空的话空着不填】
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=sendcloud
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

SEND_CLOUD_USER= cbdb_inputting_test_vlzUri 【等会注册sendCloud的用户名】
SEND_CLOUD_KEY= g8Naaaaaaaaaa【等会注册sendCloud中的生成的key】

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
（3）生成vendor文件，cd C:\Users\CBDB\cbdb-online-main-server-develop到指定的cbdb下载文件目录，然后执行：composer install
（4）生成.env中的APP_KEY，即在该目录下执行php artisan key:generate
（5）执行php artisan serve，浏览器看看http://localhost:8888 是否可以看到项目主页【注意这是本地测试，还没有搭建在服务器上，所以一旦关闭，进程就会终止，所以我们需要将其转换为Apache的守护进程】

**3、搭建lavarel项目到Apache服务器**
（1）注意找到apache的配置文件D:\Software\Wamp\wamp64\apache\conf\httpd.conf，以及D:\Software\Wamp\wamp64\apache\conf\extra\httpd-vhosts.conf。前面的配置端口（前面已经配置），后面配置该端口的相关服务与项目的映射关系，如下：。
在httpd.conf中
`Listen 0.0.0.0:8888
Listen [::0]:8888`

在httpd-vhosts.conf中，我这里不知道为什么贴补进去这个</>反标签，大家可以参加这个底下这个图：
![image](https://user-images.githubusercontent.com/42427893/71448740-c9999380-277a-11ea-872c-bca85449fb2e.png)

（2）windows防火墙增加一条放开8888端口的TCP入口与出口，重启wamp，运行http://你的ip地址:8888看到项目首页即可

**4、一些其他问题：**
（1）历史记录报错问题：根据台湾中研院工程师的反馈，我们需要将数据库中record表与user表进行一一对应，所以目前我们将record复制一份为record.copy，然后清空record表即可；
（2）注册问题，这里需要注册一个sendCloud服务，具体方式是首先获取一个邮箱，假设是A【这里非常关键】（这里使用cbdb的gmail即可），然后https://www.sendcloud.net/ 中注册和登录一个账号绑定A，这里会有一个用户账号，对应.env文件中的SEND_CLOUD_USER，在sendcloud中使用生成key的操作记住这个key，复制到.env的SEND_CLOUD_KEY中。同时sendcloud中添加在即要用的模板，模板名字假设是B【注意非常关键】，内容是你要输出的形式，具体语法可以参加sendcloud，比如：其中%name%是CBDB录入系统注册账号，%url%是向CBDB录入系统的注册账号的邮箱发送的激活url，一旦用户在CBDB录入系统点击注册后，Sendcloud向这个邮箱地址发一封邮件，邮件内容为下面

尊敬的用户%name%：
        恭喜您，已经成功注册您的CBDB录入系统账号，请点击验证您的邮箱：
%url%

然后，在项目C:\Users\CBDB\cbdb-online-main-server-develop\app\Http\Controllers\Auth中找到代码：
`    private function sendVerifyEmailTo($user)
    {
        $bind_data = [
            'url' => route('email.verify', ['token' => $user->confirmation_token]),
            'name' => $user->name
        ];
        $template = new SendCloudTemplate('这里填你的模板名字B ', $bind_data);
        Mail::raw($template, function ($message) use ($user) {
            $message->from('这里填你的邮箱A', 'CBDB');
            $message->to($user->email);
        });
}`

PS：下图中1对应SEND_CLOUD_USER，2对应SEND_CLOUD_KEY，3对应B
 
![image](https://user-images.githubusercontent.com/42427893/71448651-83900000-2779-11ea-9838-3d378e992a71.png)

**Comment by sudoghut** [comment]
update apache info. for 在httpd-vhosts.conf中，我这里不知道为什么贴不进去这个</>反标签，大家可以参加这个底下这个图：

```
<VirtualHost *:8888>
    ServerAdmin alice@bob      
    ServerName XXX.XXX.XXX.XXX              
    DocumentRoot C:\Users\CBDB\cbdb_input\public
    ErrorLog "C:\Users\CBDB\cbdb_input\logs\error.log"     
    <Directory  "C:\Users\CBDB\cbdb_input\public">
	Options +Indexes +Includes +FollowSymLinks +MultiViews
    	AllowOverride All
    	Require all granted
        DirectoryIndex index.php
    </Directory>
</VirtualHost>
```
