### ISSUE TITLE
在出處頁面的頁碼中不能輸入包含 - 內容  

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#62]
如果在錄入系統出處頁面的頁碼中包含 -，會報錯如下：

![image](https://user-images.githubusercontent.com/8538710/72778238-4e30e200-3c53-11ea-8527-b581ce008e88.png)

原因是出處的 joint primary key 是人名 id，書名 id 和頁碼信息。在當前錄入系統的 URL 中，利用 - 作為連接 joint primary key 的符號。一旦在頁碼這個開放字符串輸入的欄位中輸入含 - 的字符串（意義是從第幾頁到第幾頁），系統會將輸入的 - 當成分隔 primary keys 的符號，建構如下 URL：

http://162.105.134.121/basicinformation/24579/sources/24579-27147-811-812/edit

出處的 primary keys 原本是三個，而在這個例子裡面，因為對 - 的錯誤解析變成了四個，所以系統報錯。當前臨時解決方案是，把需要輸入 - 的地方替換成 ~。因此從 URL 解析 primary keys 便正常了：

http://162.105.134.121/basicinformation/24579/sources/24579-27147-811~812/edit

在錄入系統裡面，開放字符串錄入的欄位還有 assoc_data 的 c_text_title。希望一起討論是否有辦法允許用戶在出處的頁碼，以及社會關係的作品標題(c_text_title)中錄入含有 -  的字符串呢？感謝！

**Comment by s8714081** [comment]
1.在2019.10.29處理[assoc_data社會關係的聯合主鍵]解析(-)時，曾遇過資料內容包含負號(-)與斜線(/)的問題。在對(-)解析之前，先將負號(--)與斜線(/)置換為(-minus)與((slash))，這樣解析(-)時就能正確對應了，解析(-)之後再置換回原本的。
當時對於c_text_title這一個欄位的資料分析，有負號也有斜線，所以程式中有做特別的判斷，所以c_text_title目前是可以儲存負號與斜線。

2.欄位中需要保存(-)的資料，這一欄需要放在聯合主鍵的最後面，才不會干擾到聯合主鍵前面欄位的判別，易於組合出正確的欄位資料。

3.這次source資料表的c_pages欄位可以比照辦理，進行程式修改，已可正確儲存負號(-)了，程式修改後並已測試新增、修改、刪除、查詢等功能。

4.程式已經推送至github支線issue62，申請合併至develop，請協助code review，謝謝^_^
