### ISSUE TITLE
“行政單位等級编码表”無法刪除代碼

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#7]
點擊當前“行政單位等級编码表”之後，可以看到“操作”的方法只有“edit”

![1](https://user-images.githubusercontent.com/8538710/48838502-8294de00-edc3-11e8-90bc-5b93a343888e.png)

有時候用戶會需要刪除代碼，是否可以允許用戶可以刪除記錄呢？

![2](https://user-images.githubusercontent.com/8538710/48838564-b40da980-edc3-11e8-8252-8e9a5fceec0d.png)

感謝！

**Comment by s8714081** [comment]
1.發現到[Codes 编码表]的刪除功能，按下任何一筆，固定都會刪除列表的第一筆資料，而不是刪除指定的資料，我先修改了[Codes 编码表]的刪除功能，使其能刪除指定的資料。
2.增加[行政單位等級编码表]的刪除功能。更新在分支bug1的commit '20181207bug1。
