### ISSUE TITLE
[北大小组]根据享年推算生卒年的算法没加一

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#8]
當前錄入系統有通過享年去推算生卒年，非常方便用戶錄入。在工作中發現，推算的方法是按照現代人的年歲來算的，而古代人出生的時候就記作一歲。所以推算的算法裡面需要再多加一。麻煩修復一下，感謝啦

**Comment by ma-ji** [comment]
哈哈，虚岁。

**Comment by s8714081** [comment]
修改程式：resources/views/biogmains/basicinformation/edit.blade.php (第383行)
let deathage = death - birth + 1;
$('input[name=c_death_age]').val(deathage);
![1](https://user-images.githubusercontent.com/6869447/49571968-a173a280-f975-11e8-8b05-765b7238b79f.PNG)
