### ISSUE TITLE
保存職官信息的時候偶然出現 c_addr_id, c_addr, c_source 出錯，但無法復現

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-online-main-server#9]
北大小組在進行錄入工作的時候，發現有些職官信息在第一次錄入的時候會報錯。奇怪的是，再一次錄入之前的信息，就能正常錄入系統了。這些錯誤并不能復現。

下圖中是出錯狀況下的截圖，這些錯誤都在重覆一次錄入之後消失，所以並不能復現。但是希望能透過報錯資訊找到一些線索。感謝！

![office2](https://user-images.githubusercontent.com/8538710/49362440-bfdd6200-f719-11e8-861b-85a53ee1a2fe.png)

![office3](https://user-images.githubusercontent.com/8538710/49362441-c075f880-f719-11e8-923d-b5fbf0a2957b.jpg)

![office1](https://user-images.githubusercontent.com/8538710/49362506-ed2a1000-f719-11e8-830a-cae92237478c.jpg)

**Comment by s8714081** [comment]
1.入仕Entry這邊的聯合主鍵，我只有組合3組數值，person id-入仕法(entry_code)-次序(entry_sequence)，

之前聯合主鍵曾組合10組數值，但因為這個入仕Entry的表單有欄位允許null空值，這樣組合出的聯合主鍵會有空白片段，所以我先精簡為3組數值。

錯誤原因判斷，當一個人有兩筆入仕Entry資料，而這兩筆的入仕法(entry_code)與次序(entry_sequence)是相同的，就會有錯誤訊息，

舉例，444833這位前輩，他有兩筆入仕Entry資料，入仕法都為[92 割據自立]，次序都為[1]，這兩筆資料的聯合主鍵都會是[444833-92-1]。

所以要減少這種情況，請再挑選2欄必填的欄位給我，我修改聯合主鍵的組合，就可以減少這種情況了。


2.官名Postings這邊是以官名(office_id)-posting_id組合成為聯合主鍵，除了上次發現只有一筆[c_posting_id=298136]是重複的，幾乎可以視作primary key。

不像是因為主鍵重複而產生的問題，需要再觀察。

**Comment by sudoghut** [comment]
抱歉這麼久才回復您。

1，CBDB 的 ENTRY_DATA 裡面我們總共設置了 10 個 primary keys。我把這些 primary keys 的名稱和 default value 放在附檔中了。是否可以在入仕 ENTRY 的 input interface 裡面做一個邏輯，當這些欄位為空的時候，就按照附檔中的 default value 來自動填充欄位內容呢？感謝！

[entry data primary keys.xlsx](https://github.com/cbdb-project/cbdb-online-main-server/files/2682688/entry.data.primary.keys.xlsx)

2，c_posting_id=298136 的 duplicate 已經修復。在 POSTED_TO_OFFICE_DATA 表中 c_posting_id 可以視作 primary key。

這週的錄入中職官數據出現了更多的問題，可能我們確實要好好討論和思考一下如何來處理（譬如是否可以在代碼中加入 catch error 的臨時代碼來診斷問題呢？）下面的三張圖片是北大錄入小組這週錄入工作反饋錯誤中的一部分：

![office_20181215_3](https://user-images.githubusercontent.com/8538710/50044379-90d1d380-00bd-11e9-89ce-d19cce04231e.png)
![office_20181215_1](https://user-images.githubusercontent.com/8538710/50044380-916a6a00-00bd-11e9-9c8a-4cb75896b755.jpg)
![office_20181215_2](https://user-images.githubusercontent.com/8538710/50044381-916a6a00-00bd-11e9-80af-dc76687688dd.png)

奇怪的是，這些錯誤數據都在第二次或者第三次重覆錄入的時候能夠錄入進去了。另外，關於第二點職官問題的延伸，在工作的時候，也發現錄入 source 的時候報錯。為了方便參考和對比，也把報錯的圖放在這裡：

![source_20181215_1](https://user-images.githubusercontent.com/8538710/50044413-fde56900-00bd-11e9-9b2d-9c1d2fedeebd.png)

麻煩您了！感謝！

**Comment by s8714081** [comment]
官名的聯合主鍵使用官名[office_id]與[posting_id]組合而成，當官名修改時，聯合主鍵要跟著跳轉，之前的版本忘記跳轉了，現已修正。

更新至bug2支線，20181218修改[官名]跳轉問題。
